"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {api} from "../../lib/api";
import {Sidebar} from "../../components/sidebar";

type NotificationItem={id:string;notification_type:string;title:string;body:string;entity_type:string|null;entity_id:string|null;read_at:string|null;created_at:string};
export default function NotificationsPage(){
 const [items,setItems]=useState<NotificationItem[]>([]),[unread,setUnread]=useState(0),[error,setError]=useState(""),[loading,setLoading]=useState(true),[permission,setPermission]=useState("default"),[busy,setBusy]=useState(false);
 const known=useRef<Set<string>>(new Set());const initialized=useRef(false);
 const load=useCallback(async(notify=false)=>{try{const r=await api<{data:NotificationItem[];unreadCount:number}>("/api/notifications?limit=50");if(notify&&initialized.current&&typeof window!=="undefined"&&"Notification"in window&&Notification.permission==="granted"){for(const n of r.data){if(!known.current.has(n.id)){new Notification(n.title,{body:n.body,tag:n.id});}}}known.current=new Set(r.data.map(n=>n.id));initialized.current=true;setItems(r.data);setUnread(r.unreadCount);setError("");}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل الإشعارات")}finally{setLoading(false)}},[]);
 useEffect(()=>{if(typeof window!=="undefined"&&"Notification"in window)setPermission(Notification.permission);void load();const timer=window.setInterval(()=>void load(true),30000);return()=>window.clearInterval(timer)},[load]);
 async function enable(){if(!("Notification"in window)){setError("المتصفح لا يدعم إشعارات سطح المكتب.");return}const result=await Notification.requestPermission();setPermission(result);if(result==="granted")setError("");}
 async function markRead(id:string){setBusy(true);try{await api("/api/notifications/"+id+"/read",{method:"POST"});setItems(old=>old.map(n=>n.id===id?{...n,read_at:n.read_at||new Date().toISOString()}:n));setUnread(n=>Math.max(0,n-1))}catch(e){setError(e instanceof Error?e.message:"تعذر تحديث الإشعار")}finally{setBusy(false)}}
 async function markAll(){setBusy(true);try{await api("/api/notifications/read-all",{method:"POST"});setItems(old=>old.map(n=>({...n,read_at:n.read_at||new Date().toISOString()})));setUnread(0)}catch(e){setError(e instanceof Error?e.message:"تعذر تعليم الإشعارات كمقروءة")}finally{setBusy(false)}}
 return <div className="app-shell"><Sidebar active="/notifications"/><main className="main"><header className="topbar"><div><h1 className="page-title">الإشعارات</h1><p className="page-subtitle">تنبيهات المهام وتحديثات النظام المرتبطة بحسابك.</p></div><div className="row-actions"><button className="secondary-btn" onClick={()=>void enable()}>{permission==="granted"?"إشعارات المتصفح مفعّلة":"تفعيل إشعارات المتصفح"}</button>{unread>0&&<button className="primary-button" disabled={busy} onClick={()=>void markAll()}>تعليم الكل كمقروء</button>}</div></header><section className="content">{error&&<div className="alert error">{error}</div>}{permission==="denied"&&<div className="alert">إشعارات المتصفح محظورة من إعدادات المتصفح. تقدر تراجع صلاحيات الموقع من إعدادات المتصفح.</div>}<section className="card"><div className="card-header"><h2 className="card-title">آخر التنبيهات</h2><span className="count-badge">{unread} غير مقروء</span></div>{loading?<div className="empty">جارٍ تحميل الإشعارات...</div>:!items.length?<div className="empty">لا توجد إشعارات حتى الآن. ستظهر هنا تنبيهات المهام والتحديثات الجديدة.</div>:<div className="notification-list">{items.map(n=><article key={n.id} className={"notification-item"+(n.read_at?"":" unread")}><div className="notification-copy"><div className="notification-heading"><strong>{n.title}</strong>{!n.read_at&&<span className="status pending">جديد</span>}</div><p>{n.body}</p><time>{new Date(n.created_at).toLocaleString("ar-EG")}</time></div><div className="row-actions">{n.entity_type==="task"&&<a className="secondary-btn" href="/tasks">عرض المهام</a>}{!n.read_at&&<button className="secondary-btn" disabled={busy} onClick={()=>void markRead(n.id)}>مقروء</button>}</div></article>)}</div>}</section></section></main></div>;
}
