"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { api } from "../../lib/api";
import { Sidebar, usePermissions } from "../../components/sidebar";

type Employee={id:string;code:string;full_name:string;is_active:boolean};
type Assignee={employee_id:string;employee_code:string;employee_name:string};
type Task={id:string;code:string;title:string;description:string|null;status:string;priority:string;due_date:string|null;created_at:string;creator_username:string;assignees:Assignee[];comment_count:number};
type Comment={id:string;body:string;author_username:string;created_at:string};
const statuses:Record<string,string>={OPEN:"جديدة",IN_PROGRESS:"جاري التنفيذ",BLOCKED:"متوقفة",COMPLETED:"مكتملة",CANCELLED:"ملغاة"};
const priorities:Record<string,string>={LOW:"منخفضة",NORMAL:"عادية",HIGH:"مهمة",URGENT:"عاجلة"};
const today=()=>new Date().toISOString().slice(0,10);
export default function TasksPage(){
 const {has}=usePermissions();
 const [tasks,setTasks]=useState<Task[]>([]),[employees,setEmployees]=useState<Employee[]>([]);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const canManageTasks=has("tasks.create")||has("tasks.edit");
 const [showForm,setShowForm]=useState(false),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[priority,setPriority]=useState("NORMAL"),[dueDate,setDueDate]=useState(""),[assignees,setAssignees]=useState<string[]>([]);
 const [search,setSearch]=useState(""),[statusFilter,setStatusFilter]=useState(""),[commentTask,setCommentTask]=useState<Task|null>(null),[comments,setComments]=useState<Comment[]>([]),[commentBody,setCommentBody]=useState(""),[commentBusy,setCommentBusy]=useState(false);
 async function load(){setLoading(true);setError("");try{const t=await api<{data:Task[]}>("/api/tasks");setTasks(t.data);if(has("tasks.create")||has("tasks.edit")){const e=await api<{data:Employee[]}>("/api/employees");setEmployees(e.data.filter(x=>x.is_active));}}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل المهام")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[canManageTasks]);
 const visible=useMemo(()=>tasks.filter(t=>(!statusFilter||t.status===statusFilter)&&(!search||[t.code,t.title,t.description||"",...t.assignees.map(a=>a.employee_name)].join(" ").toLowerCase().includes(search.toLowerCase()))),[tasks,statusFilter,search]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{await api("/api/tasks",{method:"POST",body:JSON.stringify({title,description:description||null,priority,dueDate:dueDate||null,assigneeEmployeeIds:assignees})});setTitle("");setDescription("");setPriority("NORMAL");setDueDate("");setAssignees([]);setShowForm(false);await load()}catch(e){setError(e instanceof Error?e.message:"تعذر إنشاء المهمة")}finally{setSaving(false)}}
 async function updateStatus(t:Task,status:string){setError("");try{await api("/api/tasks/"+t.id,{method:"PATCH",body:JSON.stringify({status})});await load()}catch(e){setError(e instanceof Error?e.message:"تعذر تحديث حالة المهمة")}}
 async function openComments(t:Task){setCommentTask(t);setCommentBody("");try{const r=await api<{data:Comment[]}>("/api/tasks/"+t.id+"/comments");setComments(r.data)}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل التعليقات")}}
 async function addComment(e:FormEvent){e.preventDefault();if(!commentTask||!commentBody.trim())return;setCommentBusy(true);try{await api("/api/tasks/"+commentTask.id+"/comments",{method:"POST",body:JSON.stringify({body:commentBody})});setCommentBody("");await openComments(commentTask);await load()}catch(e){setError(e instanceof Error?e.message:"تعذر إضافة التعليق")}finally{setCommentBusy(false)}}
 const canUpdate=has("tasks.edit")||has("tasks.update_own");
 return <div className="app-shell"><Sidebar active="/tasks"/><main className="main">
  <header className="topbar"><div><h1 className="page-title">إدارة المهام</h1><p className="page-subtitle">إنشاء المهام، توزيع المسؤوليات، متابعة المواعيد والتعليقات وحالة التنفيذ.</p></div>{has("tasks.create")&&<button className="primary-button" onClick={()=>setShowForm(v=>!v)}>{showForm?"إلغاء":"＋ مهمة جديدة"}</button>}</header>
  <section className="content">
   {error&&<div className="alert error">{error}</div>}
   <div className="stats"><article className="card stat"><div className="stat-label">كل المهام</div><div className="stat-value">{tasks.length}</div></article><article className="card stat warning"><div className="stat-label">جديدة</div><div className="stat-value">{tasks.filter(t=>t.status==="OPEN").length}</div></article><article className="card stat accent"><div className="stat-label">قيد التنفيذ</div><div className="stat-value">{tasks.filter(t=>t.status==="IN_PROGRESS").length}</div></article><article className="card stat"><div className="stat-label">مكتملة</div><div className="stat-value">{tasks.filter(t=>t.status==="COMPLETED").length}</div></article></div>
   {showForm&&has("tasks.create")&&<form className="card form-card" onSubmit={submit}><div className="card-header"><h2 className="card-title">إنشاء مهمة جديدة</h2></div><div className="form-grid">
    <label>عنوان المهمة<input value={title} onChange={e=>setTitle(e.target.value)} required minLength={3} maxLength={240} placeholder="مثال: مراجعة مخزون الخامات"/></label>
    <label>الأولوية<select value={priority} onChange={e=>setPriority(e.target.value)}>{Object.entries(priorities).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
    <label>تاريخ الاستحقاق<input type="date" min={today()} value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label>
    <label>الموظفون المكلفون<select multiple value={assignees} onChange={e=>setAssignees(Array.from(e.target.selectedOptions).map(o=>o.value))} style={{minHeight:112}}>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name} · {x.code}</option>)}</select><small>يمكن اختيار أكثر من موظف بالضغط المطوّل أو Ctrl.</small></label>
    <label style={{gridColumn:"1 / -1"}}>التفاصيل<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} maxLength={4000} placeholder="المطلوب، خطوات التنفيذ، وأي ملاحظات..."/></label>
   </div><div className="form-actions"><button className="primary-button" disabled={saving||title.trim().length<3}>{saving?"جارٍ الحفظ...":"حفظ المهمة"}</button></div></form>}
   <section className="card"><div className="card-header"><h2 className="card-title">قائمة المهام</h2><span className="count-badge">{visible.length}</span></div>
    <div className="toolbar"><input placeholder="بحث بالكود أو العنوان أو الموظف..." value={search} onChange={e=>setSearch(e.target.value)}/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">كل الحالات</option>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>
    {loading?<div className="empty">جارٍ تحميل المهام...</div>:!visible.length?<div className="empty">لا توجد مهام مطابقة. أنشئ أول مهمة من الزر بالأعلى.</div>:<div className="table-wrap"><table><thead><tr><th>المهمة</th><th>المكلفون</th><th>الأولوية</th><th>الاستحقاق</th><th>الحالة</th><th>التعليقات</th><th>تحديث</th></tr></thead><tbody>{visible.map(t=><tr key={t.id}><td><div className="strong">{t.title}</div><div className="form-hint">{t.code} · أنشأها {t.creator_username}</div>{t.description&&<div className="task-description">{t.description}</div>}</td><td>{t.assignees.length?t.assignees.map(a=>a.employee_name).join("، "):"غير مسندة"}</td><td><span className={"status task-priority-"+String(t.priority||"NORMAL").toLowerCase()}>{priorities[t.priority]||t.priority}</span></td><td>{t.due_date?new Date(t.due_date+"T00:00:00").toLocaleDateString("ar-EG"):"بدون موعد"}{t.due_date&&t.status!=="COMPLETED"&&t.status!=="CANCELLED"&&t.due_date<today()&&<div className="task-overdue">متأخرة</div>}</td><td><span className={"status "+(t.status==="COMPLETED"?"success":t.status==="BLOCKED"?"danger":t.status==="IN_PROGRESS"?"warning":"muted")}>{statuses[t.status]||t.status}</span></td><td><button className="secondary-btn" onClick={()=>openComments(t)}>عرض ({t.comment_count})</button></td><td>{canUpdate&&t.status!=="CANCELLED"&&t.status!=="COMPLETED"?<select value={t.status} onChange={e=>updateStatus(t,e.target.value)}>{Object.entries(statuses).filter(([v])=>v!=="CANCELLED").map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:t.status==="COMPLETED"?"—":"للقراءة فقط"}</td></tr>)}</tbody></table></div>}
   </section>
  </section>
  {commentTask&&<div className="modal-backdrop" onClick={()=>setCommentTask(null)}><div className="modal-card" onClick={e=>e.stopPropagation()}><div className="card-header"><div><h2 className="card-title">تعليقات المهمة</h2><div className="form-hint">{commentTask.title}</div></div><button className="secondary-btn" onClick={()=>setCommentTask(null)}>إغلاق</button></div><div className="task-comments">{comments.map(c=><article className="task-comment" key={c.id}><div><strong>{c.author_username}</strong><span>{new Date(c.created_at).toLocaleString("ar-EG")}</span></div><p>{c.body}</p></article>)}{!comments.length&&<div className="empty">لا توجد تعليقات حتى الآن.</div>}</div>{has("tasks.comment")&&<form onSubmit={addComment} className="task-comment-form"><label>إضافة تعليق<textarea value={commentBody} onChange={e=>setCommentBody(e.target.value)} required maxLength={4000} rows={3}/></label><button className="primary-button" disabled={commentBusy||!commentBody.trim()}>{commentBusy?"جارٍ الإرسال...":"إضافة التعليق"}</button></form>}</div></div>}
 </main></div>;
}
