"use client";
import {FormEvent,useEffect,useState} from "react";
import {api} from "../../lib/api";
import { Sidebar, usePermissions } from "../../components/sidebar";
type Item={id:string;code:string;name:string};
type Location=Item&{warehouse_id:string};
type Delivery={id:string;code:string;destination:string;status:string;line_count:number;created_at:string};
const labels:Record<string,string>={READY:"جاهز للخروج",RELEASED:"خرج",DRAFT:"مسودة",CANCELLED:"ملغى"};
export default function DeliveriesPage(){
 const {has}=usePermissions();
 const [products,setProducts]=useState<Item[]>([]),[warehouses,setWarehouses]=useState<Item[]>([]),[locations,setLocations]=useState<Location[]>([]),[items,setItems]=useState<Delivery[]>([]),[productId,setProductId]=useState(""),[warehouseId,setWarehouseId]=useState(""),[locationId,setLocationId]=useState(""),[quantity,setQuantity]=useState(""),[destination,setDestination]=useState(""),[scan,setScan]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 async function load(){try{const [p,w,l,d]=await Promise.all([api<{data:Item[]}>("/api/products"),api<{data:Item[]}>("/api/warehouses"),api<{data:Location[]}>("/api/warehouse/locations"),api<{data:Delivery[]}>("/api/delivery-permissions")]);setProducts(p.data);setWarehouses(w.data);setLocations(l.data);setItems(d.data)}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل التسليمات")}}
 useEffect(()=>{void load()},[]);
 async function create(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{await api("/api/delivery-permissions",{method:"POST",body:JSON.stringify({destination,lines:[{productId,warehouseId,locationId,quantity:Number(quantity)}]})});setDestination("");setQuantity("");await load()}catch(e){setError(e instanceof Error?e.message:"تعذر إنشاء الإذن")}finally{setSaving(false)}}
 async function release(id:string){try{const code=scan.trim();if(!code){setError("اكتب كود إذن التسليم بعد مسحه");return}await api("/api/delivery-permissions/"+id+"/release",{method:"POST",body:JSON.stringify({scanCode:code})});setScan("");await load()}catch(e){setError(e instanceof Error?e.message:"تعذر إخراج الإذن")}}
 const currentLocations=locations.filter(x=>x.warehouse_id===warehouseId);
 return <div className="app-shell"><Sidebar active="/deliveries"/>
 <main className="main"><header className="topbar"><div><h1 className="page-title">إذن تسليم</h1><p className="page-subtitle">إنشاء الإذن ومسحه قبل خروج البضاعة</p></div></header><section className="content">{error&&<div className="alert error">{error}</div>}
 {has("deliveries.create")&&<form className="card form-card" onSubmit={create}><div className="card-header"><h2 className="card-title">إذن جديد</h2></div><div className="form-grid"><label>جهة التسليم<input value={destination} onChange={e=>setDestination(e.target.value)} required/></label><label>المنتج<select value={productId} onChange={e=>setProductId(e.target.value)} required><option value="">اختر المنتج</option>{products.map(x=><option key={x.id} value={x.id}>{x.name} — {x.code}</option>)}</select></label><label>المخزن<select value={warehouseId} onChange={e=>{setWarehouseId(e.target.value);setLocationId("")}} required><option value="">اختر المخزن</option>{warehouses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>المكان<select value={locationId} onChange={e=>setLocationId(e.target.value)} required><option value="">اختر المكان</option>{currentLocations.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label><label>الكمية<input type="number" min="0.001" step="0.001" value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label></div><div className="form-actions"><button className="primary-button" disabled={saving}>{saving?"جارٍ الإنشاء...":"إنشاء إذن تسليم"}</button></div></form>}
 <section className="card"><div className="card-header"><h2 className="card-title">أذونات التسليم</h2></div><div className="table-wrap"><table><thead><tr><th>الكود</th><th>الجهة</th><th>السطور</th><th>التاريخ</th><th>الحالة</th><th>مسح قبل الخروج</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td className="mono">{x.code}</td><td className="strong">{x.destination}</td><td>{x.line_count}</td><td>{new Date(x.created_at).toLocaleString("ar-EG")}</td><td><span className={"status "+x.status.toLowerCase()}>{labels[x.status]||x.status}</span></td><td>{x.status==="READY"&&has("deliveries.release")&&<div className="row-actions"><input value={scan} onChange={e=>setScan(e.target.value)} placeholder="امسح كود الإذن"/><button className="approve-button" onClick={()=>release(x.id)}>تأكيد الخروج</button></div>}</td></tr>)}{!items.length&&<tr><td colSpan={6}>لا توجد أذونات.</td></tr>}</tbody></table></div></section>
 </section></main></div>
}