"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {api} from "../../lib/api";
import {Sidebar,usePermissions} from "../../components/sidebar";
import {Code39Barcode} from "../../components/code39-barcode";
import {SearchableSelect} from "../../components/searchable-select";
type Item={id:string;code:string;name:string};
type Location=Item&{warehouse_id:string};
type Warehouse=Item&{warehouse_type:string};
type Order=Item&{order_name:string};
type Delivery={id:string;code:string;destination:string;status:string;line_count:number;created_at:string;order_code:string|null;order_name:string|null};
const labels:Record<string,string>={READY:"جاهز للخروج",RELEASED:"خرج",DRAFT:"مسودة",CANCELLED:"ملغى"};
export default function DeliveriesPage(){
 const {has}=usePermissions();const [printItem,setPrintItem]=useState<Delivery|null>(null),[products,setProducts]=useState<Item[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[locations,setLocations]=useState<Location[]>([]),[orders,setOrders]=useState<Order[]>([]),[items,setItems]=useState<Delivery[]>([]);
 const [orderId,setOrderId]=useState(""),[productId,setProductId]=useState(""),[warehouseId,setWarehouseId]=useState(""),[locationId,setLocationId]=useState(""),[quantity,setQuantity]=useState(""),[destination,setDestination]=useState(""),[scan,setScan]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 async function load(){try{const [p,w,l,o,d]=await Promise.all([api<{data:Item[]}>("/api/products"),api<{data:Warehouse[]}>("/api/warehouses"),api<{data:Location[]}>("/api/warehouse/locations"),api<{data:Order[]}>("/api/orders"),api<{data:Delivery[]}>("/api/delivery-permissions")]);setProducts(p.data);setWarehouses(w.data);setLocations(l.data);setOrders(o.data);setItems(d.data);if(!warehouseId){const ready=w.data.find(x=>x.warehouse_type==="FINISHED_GOODS");if(ready)setWarehouseId(ready.id)}}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل التسليمات")}}
 useEffect(()=>{void load()},[]);
 const orderOptions=useMemo(()=>orders.map(x=>({value:x.id,label:x.order_name,meta:x.code})),[orders]),productOptions=useMemo(()=>products.map(x=>({value:x.id,label:x.name})),[products]),warehouseOptions=useMemo(()=>warehouses.filter(x=>x.warehouse_type==="FINISHED_GOODS").map(x=>({value:x.id,label:x.name,meta:"منتجات جاهزة"})),[warehouses]),locationOptions=useMemo(()=>locations.filter(x=>x.warehouse_id===warehouseId).map(x=>({value:x.id,label:x.name})),[locations,warehouseId]);
 async function create(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{await api("/api/delivery-permissions",{method:"POST",body:JSON.stringify({orderId:orderId||null,destination,lines:[{productId,warehouseId,locationId,quantity:Number(quantity)}]})});setDestination("");setQuantity("");setOrderId("");setProductId("");await load()}catch(e){setError(e instanceof Error?e.message:"تعذر إنشاء الإذن")}finally{setSaving(false)}}
 async function release(id:string){try{const code=scan.trim();if(!code){setError("اكتب كود إذن التسليم بعد مسحه");return}await api("/api/delivery-permissions/"+id+"/release",{method:"POST",body:JSON.stringify({scanCode:code})});setScan("");await load()}catch(e){setError(e instanceof Error?e.message:"تعذر إخراج الإذن")}}
 return <div className="app-shell"><Sidebar active="/deliveries"/><main className="main"><header className="topbar"><div><h1 className="page-title">التسليمات</h1><p className="page-subtitle">التسليم يبدأ باختيار الطلب ثم المنتج من مخزن المنتجات الجاهزة، ولا يخرج شيء بدون مسح الإذن.</p></div></header><section className="content">{error&&<div className="alert error">{error}</div>}
 {has("deliveries.create")&&<form className="card form-card" onSubmit={create}><div className="card-header"><div><h2 className="card-title">تسجيل تسليم</h2><div className="form-hint">المنتج يتم اختياره بالاسم، والطلبية مرتبطة مباشرة بإذن الخروج.</div></div></div><div className="form-grid">
  <label>الطلبية<SearchableSelect value={orderId} onChange={setOrderId} options={orderOptions} placeholder="اختر الطلبية" searchPlaceholder="ابحث باسم الطلبية"/></label><label>المنتج<SearchableSelect value={productId} onChange={setProductId} options={productOptions} placeholder="اختر المنتج"/></label><label>مخزن المنتجات الجاهزة<SearchableSelect value={warehouseId} onChange={v=>{setWarehouseId(v);setLocationId("")}} options={warehouseOptions} placeholder="اختر المخزن"/></label><label>المكان<SearchableSelect value={locationId} onChange={setLocationId} options={locationOptions} placeholder="اختر المكان"/></label><label>الكمية<input inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label><label>جهة التسليم<input value={destination} onChange={e=>setDestination(e.target.value)} required/></label>
 </div><div className="form-actions"><button className="primary-button" disabled={saving}>{saving?"جارٍ الإنشاء...":"إنشاء إذن التسليم"}</button></div></form>}
 <section className="card"><div className="card-header"><h2 className="card-title">أذونات التسليم</h2></div><div className="table-wrap"><table><thead><tr><th>الطلبية</th><th>الجهة</th><th>السطور</th><th>التاريخ</th><th>الحالة</th><th>مسح قبل الخروج</th><th>طباعة</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td className="strong">{x.order_name||"بدون طلب"}</td><td>{x.destination}</td><td>{x.line_count}</td><td>{new Date(x.created_at).toLocaleString("ar-EG")}</td><td><span className={"status "+x.status.toLowerCase()}>{labels[x.status]||x.status}</span></td><td>{x.status==="READY"&&has("deliveries.release")&&<div className="row-actions"><input value={scan} onChange={e=>setScan(e.target.value)} placeholder="امسح الكود"/><button className="approve-button" onClick={()=>release(x.id)}>تأكيد</button></div>}</td><td><button className="approve-button" onClick={()=>{setPrintItem(x);setTimeout(()=>window.print(),50)}}>طباعة</button></td></tr>)}{!items.length&&<tr><td colSpan={7}>لا توجد أذونات.</td></tr>}</tbody></table></div></section>
 </section>{printItem&&<div className="print-sheet"><div className="print-brand">تذكار</div><h1>إذن تسليم</h1><Code39Barcode value={printItem.code} height={82}/><div className="print-code">{printItem.code}</div><div className="print-grid"><div><b>الطلبية</b><span>{printItem.order_name||"—"}</span></div><div><b>جهة التسليم</b><span>{printItem.destination}</span></div><div><b>عدد السطور</b><span>{printItem.line_count}</span></div><div><b>الحالة</b><span>{labels[printItem.status]||printItem.status}</span></div></div><div className="signature-row"><span>مسؤول المخزن: __________________</span><span>المستلم: __________________</span></div><p className="print-note">لا يتم خروج البضاعة إلا بعد مسح كود الإذن والتأكد من مطابقته.</p></div>}</main></div>
}
