"use client";
import {useEffect,useState} from "react";
import {api,ApiError} from "../lib/api";
import { Sidebar } from "../components/sidebar";
type Summary={production:{quantity:string;entries:number};earnings:{balance:string;earned:string;paid:string};stock:{lines:number;quantity:string};pendingPayments:number;pendingAdvances:number;orders:{total:number;active:number;completed:number}};
export default function HomePage(){
 const [summary,setSummary]=useState<Summary|null>(null),[error,setError]=useState("");
 useEffect(()=>{api<{data:Summary}>("/api/dashboard/summary").then(x=>setSummary(x.data)).catch(e=>{if(e instanceof ApiError&&e.code==="FORBIDDEN"){window.location.replace("/my-production");return}setError(e instanceof Error?e.message:"تعذر تحميل لوحة التحكم")})},[]);
 const n=(v:string|number)=>Number(v||0).toLocaleString("ar-EG",{maximumFractionDigits:2});
 return <div className="app-shell"><Sidebar active="/" />
 <main className="main"><header className="topbar"><div><h1 className="page-title">لوحة التحكم</h1><p className="page-subtitle">نظرة حقيقية على حركة المصنع اليوم</p></div><a className="user-chip" href="/settings"><div className="avatar">ت</div><div><div className="user-name">إدارة النظام</div><div className="user-role">الإعدادات والحسابات</div></div></a></header><section className="content">
 {error&&<div className="alert error">{error}</div>}
 <div className="stats"><article className="card stat"><div className="stat-label">إنتاج اليوم</div><div className="stat-value">{summary?n(summary.production.quantity):"—"}</div><div className="stat-note">{summary?summary.production.entries+" سجل معتمد":"جاري التحميل"}</div></article><article className="card stat accent"><div className="stat-label">صافي مستحقات العاملين</div><div className="stat-value">{summary?n(summary.earnings.balance):"—"}</div><div className="stat-note">المستحقات − المدفوع والسلف</div></article><article className="card stat warning"><div className="stat-label">سطور المخزون</div><div className="stat-value">{summary?summary.stock.lines:"—"}</div><div className="stat-note">أرصدة أكبر من صفر</div></article><article className="card stat neutral"><div className="stat-label">طلبات التشغيل</div><div className="stat-value">{summary?summary.orders.active:"—"}</div><div className="stat-note">{summary?summary.orders.total+" إجمالي · "+summary.orders.completed+" مكتمل":"جاري التحميل"}</div></article></div>
 <div className="grid"><section className="card"><div className="card-header"><h2 className="card-title">حالة التشغيل</h2></div><div className="card-body"><div className="quick-grid"><a className="quick" href="/orders"><strong>الطلبات</strong><span>{summary?summary.orders.active+" طلب قيد التشغيل":"فتح الطلبات"}</span></a><a className="quick" href="/production"><strong>الإنتاج</strong><span>{summary?summary.production.entries+" سجل معتمد اليوم":"فتح الإنتاج"}</span></a><a className="quick" href="/warehouse"><strong>المخزن</strong><span>{summary?summary.stock.lines+" رصيد نشط":"فتح المخزن"}</span></a><a className="quick" href="/advances"><strong>السلف</strong><span>{summary?summary.pendingAdvances+" طلب بانتظار المراجعة":"فتح السلف"}</span></a><a className="quick" href="/payments"><strong>القبض</strong><span>{summary?summary.pendingPayments+" طلب بانتظار المراجعة":"فتح القبض"}</span></a></div></div></section>
 <section className="card"><div className="card-header"><h2 className="card-title">أرقام مالية</h2></div><div className="card-body"><p>إجمالي المستحق المعتمد: <strong>{summary?n(summary.earnings.earned):"—"}</strong></p><p>إجمالي المدفوع: <strong>{summary?n(summary.earnings.paid):"—"}</strong></p><p>الرصيد الحالي: <strong>{summary?n(summary.earnings.balance):"—"}</strong></p></div></section></div>
 </section></main></div>
}