"use client";

import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {api} from "../../../lib/api";
import {Sidebar,usePermissions} from "../../../components/sidebar";

type Item={id:string;code:string;name:string};
type Dashboard={order:any;stages:any[];production:any[];movements:any[];deliveries:any[];totals:any};
type Reconciliation={order:any;products:Array<{productId:string;ordered:number;produced:number;delivered:number;stockOut:number;stockIn:number;productionVariance:number;deliveryVariance:number}>;ok:boolean};
const normalizeNumber=(v:string)=>v.replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d))).replace(/[٬،]/g,"").replace(/٫/g,".");

export default function OrderDetailPage(){
 const {id}=useParams<{id:string}>(); const {has}=usePermissions();
 const [data,setData]=useState<Dashboard|null>(null),[recon,setRecon]=useState<Reconciliation|null>(null),[error,setError]=useState(""),[stageName,setStageName]=useState(""),[outputProductName,setOutputProductName]=useState(""),[planned,setPlanned]=useState("");
 async function load(){try{const [d,r]=await Promise.all([api<{data:Dashboard}>("/api/orders/"+id+"/dashboard"),api<{data:Reconciliation}>("/api/orders/"+id+"/reconciliation")]);setData(d.data);setRecon(r.data)}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل ملف الطلب")}}
 useEffect(()=>{if(id)void load()},[id]);
 async function addStage(){if(!stageName.trim())return;try{await api("/api/orders/"+id+"/stages",{method:"POST",body:JSON.stringify({stageName:stageName.trim(),outputProductName:outputProductName.trim()||undefined,sequenceNo:(data?.stages.length??0)+1,plannedQuantity:planned?Number(normalizeNumber(planned)):undefined})});setStageName("");setOutputProductName("");setPlanned("");await load()}catch(e){setError(e instanceof Error?e.message:"تعذر إضافة المرحلة")}}
 async function editStage(stage:any){const name=window.prompt("اسم المرحلة",stage.stage_name);if(name===null)return;const product=window.prompt("المنتج الناتج",stage.output_product_name||"");const next=window.prompt("الحالة (PENDING / READY / IN_PROGRESS / COMPLETED / CANCELLED)",stage.status);if(next===null)return;try{await api("/api/order-stages/"+stage.id,{method:"PATCH",body:JSON.stringify({stageName:name.trim(),outputProductName:product?.trim()||undefined,status:next})});await load()}catch(e){setError(e instanceof Error?e.message:"تعذر تعديل المرحلة")}}
 if(!data)return <div className="app-shell"><Sidebar active="/orders"/><main className="main"><div className="content">{error?<div className="alert error">{error}</div>:<div className="empty">جارٍ تحميل ملف الطلب...</div>}</div></main></div>;
 const o=data.order;
 return <div className="app-shell"><Sidebar active="/orders"/><main className="main">
  <header className="topbar"><div><button className="link-button" onClick={()=>window.location.href="/orders"}>← العودة للطلبات</button><h1 className="page-title">{o.order_name}</h1><p className="page-subtitle">{o.code}{o.customer_name?" · "+o.customer_name:""} · {o.status}</p></div></header>
  <section className="content">
   {error&&<div className="alert error">{error}</div>}
   <div className="stats">
    <article className="card stat"><div className="stat-label">تكلفة الإنتاج</div><div className="stat-value">{Number(data.totals.production_cost||0).toLocaleString("ar-EG",{maximumFractionDigits:2})}</div><div className="stat-note">أجور الإنتاج المعتمدة</div></article>
    <article className="card stat accent"><div className="stat-label">تكلفة المسحوبات</div><div className="stat-value">{Number(data.totals.stock_out_cost||0).toLocaleString("ar-EG",{maximumFractionDigits:2})}</div><div className="stat-note">صرف المخزن المرتبط بالطلب</div></article>
    <article className="card stat warning"><div className="stat-label">تكلفة الداخل</div><div className="stat-value">{Number(data.totals.stock_in_cost||0).toLocaleString("ar-EG",{maximumFractionDigits:2})}</div><div className="stat-note">إدخالات مرتبطة بالطلب</div></article>
    <article className="card stat neutral"><div className="stat-label">الكمية المنجزة</div><div className="stat-value">{Number(o.completed_quantity||0).toLocaleString("ar-EG")}</div><div className="stat-note">تتحدث مع التشغيل</div></article>
   </div>
   <section className="card" style={{marginBottom:16}}><div className="card-header"><div><h2 className="card-title">بيانات الطلب</h2><div className="form-hint">تاريخ الطلب {o.order_date} · بداية التسليم {o.delivery_start_date||"—"} · آخر دفعة {o.last_delivery_date||o.due_date||"—"}</div></div></div><div className="order-detail-meta"><div><span>العميل</span><strong>{o.customer_name||"—"}</strong></div><div><span>الحالة</span><strong>{o.status}</strong></div><div><span>ملاحظات</span><strong>{o.notes||"—"}</strong></div></div></section>
   <section className="card" style={{marginBottom:16}}><div className="card-header"><div><h2 className="card-title">مراحل الطلب</h2><div className="form-hint">يمكن تعديل المرحلة أو المنتج الناتج أو ترتيبها من هنا.</div></div></div>
    {has("orders.manage_stages")&&<div className="stage-add-bar"><input placeholder="اكتب اسم المرحلة" value={stageName} onChange={e=>setStageName(e.target.value)}/><input placeholder="اكتب المنتج الناتج" value={outputProductName} onChange={e=>setOutputProductName(e.target.value)}/><input inputMode="decimal" placeholder="الكمية المخططة" value={planned} onChange={e=>setPlanned(e.target.value)}/><button className="primary-button" onClick={addStage}>إضافة</button></div>}
    <div className="table-wrap"><table><thead><tr><th>#</th><th>المرحلة</th><th>المنتج الناتج</th><th>المخطط</th><th>المنجز</th><th>الحالة</th><th></th></tr></thead><tbody>{data.stages.map((x,i)=><tr key={x.id}><td>{i+1}</td><td>{x.stage_name}</td><td>{x.output_product_name||"—"}</td><td>{x.planned_quantity??"—"}</td><td>{x.completed_quantity}</td><td><span className="status">{x.status}</span></td><td>{has("orders.manage_stages")&&<button className="link-button" onClick={()=>editStage(x)}>تعديل</button>}</td></tr>)}</tbody></table></div>
   </section>
   <div className="grid">
    <section className="card"><div className="card-header"><h2 className="card-title">إنتاج الطلب</h2></div><div className="table-wrap"><table><thead><tr><th>التاريخ</th><th>الموظف</th><th>المرحلة</th><th>النوع</th><th>الكمية</th><th>الأساسي</th><th>البونص</th><th>الخصم</th><th>إجمالي العمالة</th><th>المدفوع</th><th>المتبقي</th><th>الحالة</th></tr></thead><tbody>{data.production.map(x=><tr key={x.id}><td>{x.work_date}</td><td>{x.employee_name}</td><td>{x.stage_name}</td><td>{x.production_type_name||"—"}</td><td>{x.quantity}</td><td>{Number(x.earning_amount||0).toLocaleString("ar-EG",{maximumFractionDigits:2})}</td><td>{Number(x.bonus_amount||0).toLocaleString("ar-EG",{maximumFractionDigits:2})}</td><td>{Number(x.deduction_amount||0).toLocaleString("ar-EG",{maximumFractionDigits:2})}</td><td className="money strong">{Number(x.total_earning_amount||x.earning_amount||0).toLocaleString("ar-EG",{maximumFractionDigits:2})}</td><td>{Number(x.paid_amount||0).toLocaleString("ar-EG",{maximumFractionDigits:2})}</td><td>{Number(x.remaining_amount||0).toLocaleString("ar-EG",{maximumFractionDigits:2})}</td><td><span className={"status "+(Number(x.remaining_amount||0)<=0&&x.status==="APPROVED"?"approved":"")}>{Number(x.remaining_amount||0)<=0&&x.status==="APPROVED"?"مدفوع بالكامل":x.status==="APPROVED"?"غير مكتمل الدفع":x.status==="PENDING"?"معلق":x.status}</span></td></tr>)}{!data.production.length&&<tr><td colSpan={12}>لا يوجد إنتاج مرتبط حتى الآن.</td></tr>}</tbody></table></div></section>
    <section className="card"><div className="card-header"><h2 className="card-title">مسحوبات المخزن</h2></div><div className="table-wrap"><table><thead><tr><th>التاريخ</th><th>المنتج</th><th>المخزن</th><th>الكمية</th><th>التكلفة</th></tr></thead><tbody>{data.movements.map(x=><tr key={x.code}><td>{new Date(x.created_at).toLocaleDateString("ar-EG")}</td><td>{x.product_name}</td><td>{x.warehouse_name}</td><td>{x.quantity}</td><td className="money">{Number(x.total_cost||0).toLocaleString("ar-EG",{maximumFractionDigits:2})}</td></tr>)}{!data.movements.length&&<tr><td colSpan={5}>لا توجد مسحوبات مرتبطة بالطلب.</td></tr>}</tbody></table></div></section>
   </div>
   <section className="card" style={{marginBottom:16}}><div className="card-header"><div><h2 className="card-title">مطابقة الطلب</h2><div className="form-hint">مقارنة المطلوب بالإنتاج المعتمد والتسليمات وحركة المخزن.</div></div><span className={recon?.ok?"status approved":"status rejected"}>{recon?(recon.ok?"متطابق":"يحتاج مراجعة"):"—"}</span></div><div className="table-wrap"><table><thead><tr><th>المنتج</th><th>المطلوب</th><th>الإنتاج المعتمد</th><th>المسلّم</th><th>خروج المخزن</th><th>دخول المخزن</th><th>فرق الإنتاج</th><th>فرق التسليم</th></tr></thead><tbody>{recon?.products.map(x=><tr key={x.productId}><td>{data?.production.find((p:any)=>p.product_id===x.productId)?.product_name||"—"}</td><td>{x.ordered}</td><td>{x.produced}</td><td>{x.delivered}</td><td>{x.stockOut}</td><td>{x.stockIn}</td><td>{x.productionVariance}</td><td>{x.deliveryVariance}</td></tr>)}{!recon?.products.length&&<tr><td colSpan={8}>لا توجد بيانات مطابقة بعد.</td></tr>}</tbody></table></div></section>
   <section className="card" style={{marginTop:16}}><div className="card-header"><h2 className="card-title">التسليمات</h2></div><div className="table-wrap"><table><thead><tr><th>الإذن</th><th>الوجهة</th><th>الكمية</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>{data.deliveries.map(x=><tr key={x.id}><td className="mono">{x.code}</td><td>{x.destination}</td><td>{x.quantity}</td><td>{x.status}</td><td>{new Date(x.created_at).toLocaleDateString("ar-EG")}</td></tr>)}{!data.deliveries.length&&<tr><td colSpan={5}>لا توجد تسليمات بعد.</td></tr>}</tbody></table></div></section>
  </section>
 </main></div>;
}
