"use client";

import {FormEvent,useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {api} from "../../../lib/api";
import {Sidebar,usePermissions} from "../../../components/sidebar";

type Item={id:string;code:string;name:string};
type Dashboard={order:any;stages:any[];production:any[];movements:any[];deliveries:any[];totals:any};
type Reconciliation={order:any;products:Array<{productId:string;ordered:number;produced:number;delivered:number;stockOut:number;stockIn:number;productionVariance:number;deliveryVariance:number}>;ok:boolean};
type PriceChange={id:string;code:string;order_stage_id:string;previous_rate:number|null;new_rate:number;scope:"NEW_ONLY"|"UNPAID_ONLY"|"ALL";reason:string;affected_entries:number;total_delta:number;created_at:string;stage_name:string;created_by_username:string;affected:Array<{employee_name:string;production_code:string;previous_earning:number;revised_earning:number;delta_amount:number}>};
const priceScopeLabels:Record<string,string>={NEW_ONLY:"الإنتاج الجديد فقط",UNPAID_ONLY:"العمليات غير المدفوعة فقط",ALL:"كل العمليات"};
const normalizeNumber=(v:string)=>v.replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d))).replace(/[٬،]/g,"").replace(/٫/g,".");

export default function OrderDetailPage(){
 const {id}=useParams<{id:string}>(); const {has}=usePermissions();
 const [data,setData]=useState<Dashboard|null>(null),[recon,setRecon]=useState<Reconciliation|null>(null),[error,setError]=useState(""),[stageName,setStageName]=useState(""),[outputProductName,setOutputProductName]=useState(""),[planned,setPlanned]=useState(""),[stageRate,setStageRate]=useState(""),[stageRateMethod,setStageRateMethod]=useState("PER_1000"),[editStageTarget,setEditStageTarget]=useState<any|null>(null),[editStageName,setEditStageName]=useState(""),[editStageProduct,setEditStageProduct]=useState(""),[editStageStatus,setEditStageStatus]=useState("PENDING"),[savingStage,setSavingStage]=useState(false),[priceChanges,setPriceChanges]=useState<PriceChange[]>([]),[priceChangeStage,setPriceChangeStage]=useState<any|null>(null),[priceChangeRate,setPriceChangeRate]=useState(""),[priceChangeScope,setPriceChangeScope]=useState<"NEW_ONLY"|"UNPAID_ONLY"|"ALL">("NEW_ONLY"),[priceChangeReason,setPriceChangeReason]=useState(""),[priceChangeSaving,setPriceChangeSaving]=useState(false);
 async function load(){try{const [d,r,p]=await Promise.all([api<{data:Dashboard}>("/api/orders/"+id+"/dashboard"),api<{data:Reconciliation}>("/api/orders/"+id+"/reconciliation"),api<{data:PriceChange[]}>("/api/orders/"+id+"/price-changes").catch(()=>({data:[]}))]);setData(d.data);setRecon(r.data);setPriceChanges(p.data)}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل ملف الطلب")}}
 useEffect(()=>{if(id)void load()},[id]);
 function beginPriceChange(stage:any){setPriceChangeStage(stage);setPriceChangeRate(String(stage.stage_rate??""));setPriceChangeScope("NEW_ONLY");setPriceChangeReason("");}
 async function submitPriceChange(e:FormEvent){e.preventDefault();if(!priceChangeStage)return;const rate=Number(normalizeNumber(priceChangeRate));if(!Number.isFinite(rate)||rate<0){setError("السعر الجديد غير صحيح");return}if(priceChangeReason.trim().length<2){setError("اكتب سبب تغيير السعر");return}setPriceChangeSaving(true);setError("");try{await api("/api/orders/"+id+"/price-changes",{method:"POST",body:JSON.stringify({orderStageId:priceChangeStage.id,newRate:rate,scope:priceChangeScope,reason:priceChangeReason.trim()})});setPriceChangeStage(null);setPriceChangeReason("");await load()}catch(e){setError(e instanceof Error?e.message:"تعذر تغيير سعر المرحلة")}finally{setPriceChangeSaving(false)}}
 async function addStage(){if(!stageName.trim())return;try{await api("/api/orders/"+id+"/stages",{method:"POST",body:JSON.stringify({stageName:stageName.trim(),outputProductName:outputProductName.trim()||undefined,sequenceNo:(data?.stages.length??0)+1,plannedQuantity:planned?Number(normalizeNumber(planned)):undefined,stageRate:stageRate?Number(normalizeNumber(stageRate)):undefined,stageRateMethod})});setStageName("");setOutputProductName("");setPlanned("");setStageRate("");setStageRateMethod("PER_1000");await load()}catch(e){setError(e instanceof Error?e.message:"تعذر إضافة المرحلة")}}
 function editStage(stage:any){setEditStageTarget(stage);setEditStageName(stage.stage_name||"");setEditStageProduct(stage.output_product_name||"");setEditStageStatus(stage.status||"PENDING")}
 async function saveStageEdit(e:FormEvent){e.preventDefault();if(!editStageTarget)return;setSavingStage(true);setError("");try{await api("/api/order-stages/"+editStageTarget.id,{method:"PATCH",body:JSON.stringify({stageName:editStageName.trim(),outputProductName:editStageProduct.trim()||undefined,status:editStageStatus})});setEditStageTarget(null);await load()}catch(e){setError(e instanceof Error?e.message:"تعذر تعديل المرحلة")}finally{setSavingStage(false)}}
 if(!data)return <div className="app-shell"><Sidebar active="/orders"/><main className="main"><div className="content">{error?<div className="alert error">{error}</div>:<div className="empty">جارٍ تحميل ملف الطلب...</div>}</div></main></div>;
 const o=data.order;
 return <div className="app-shell"><Sidebar active="/orders"/><main className="main">
  <header className="topbar"><div><button className="link-button" onClick={()=>window.location.href="/orders"}>← العودة للطلبات</button><h1 className="page-title">{o.order_name}</h1><p className="page-subtitle">{o.code}{o.customer_name?" · "+o.customer_name:""} · {o.status}</p></div></header>
  <section className="content">
   {error&&<div className="alert error">{error}</div>}
   <div className="stats">
    <article className="card stat"><div className="stat-label">تكلفة الإنتاج</div><div className="stat-value">{Number(data.totals.production_cost||0).toLocaleString("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2})}</div><div className="stat-note">أجور الإنتاج المعتمدة</div></article>
    <article className="card stat accent"><div className="stat-label">تكلفة المسحوبات</div><div className="stat-value">{Number(data.totals.stock_out_cost||0).toLocaleString("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2})}</div><div className="stat-note">صرف المخزن المرتبط بالطلب</div></article>
    <article className="card stat"><div className="stat-label">مصروفات محمّلة على الطلب</div><div className="stat-value">{Number(data.totals.order_expenses||0).toLocaleString("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2})}</div><div className="stat-note">مصروفات إدارية مرتبطة بهذه الطلبية</div></article>
    <article className="card stat neutral"><div className="stat-label">الكمية المنجزة</div><div className="stat-value">{Number(o.completed_quantity||0).toLocaleString("ar-EG")}</div><div className="stat-note">تتحدث مع التشغيل</div></article>
   </div>
   <section className="card" style={{marginBottom:16}}><div className="card-header"><div><h2 className="card-title">بيانات الطلب</h2><div className="form-hint">تاريخ الطلب {o.order_date} · بداية التسليم {o.delivery_start_date||"—"} · آخر دفعة {o.last_delivery_date||o.due_date||"—"}</div></div></div><div className="order-detail-meta"><div><span>العميل</span><strong>{o.customer_name||"—"}</strong></div><div><span>الحالة</span><strong>{o.status}</strong></div><div><span>ملاحظات</span><strong>{o.notes||"—"}</strong></div></div></section>
   <section className="card" style={{marginBottom:16}}><div className="card-header"><div><h2 className="card-title">مراحل الطلب</h2><div className="form-hint">يمكن تعديل المرحلة أو المنتج الناتج أو ترتيبها من هنا.</div></div></div>
    {has("orders.manage_stages")&&<div className="stage-add-bar"><input placeholder="اكتب اسم المرحلة" value={stageName} onChange={e=>setStageName(e.target.value)}/><input placeholder="اكتب المنتج الناتج" value={outputProductName} onChange={e=>setOutputProductName(e.target.value)}/><input inputMode="decimal" placeholder="الكمية المخططة" value={planned} onChange={e=>setPlanned(e.target.value)}/><select value={stageRateMethod} onChange={e=>setStageRateMethod(e.target.value)}><option value="PER_PIECE">بالقطعة</option><option value="PER_1000">لكل ألف</option><option value="PER_HOUR">بالساعة</option><option value="PER_DAY">باليومية</option><option value="PERCENTAGE">نسبة</option></select><input inputMode="decimal" placeholder="سعر المرحلة" value={stageRate} onChange={e=>setStageRate(e.target.value)}/><button className="primary-button" onClick={addStage}>إضافة</button></div>}
    <div className="table-wrap"><table><thead><tr><th>#</th><th>المرحلة</th><th>المنتج الناتج</th><th>سعر المرحلة</th><th>طريقة التسعير</th><th>المخطط</th><th>المنجز</th><th>الحالة</th><th></th></tr></thead><tbody>{data.stages.map((x,i)=><tr key={x.id}><td>{i+1}</td><td>{x.stage_name}</td><td>{x.output_product_name||"—"}</td><td className="money">{x.stage_rate!=null?Number(x.stage_rate).toLocaleString("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2}):"—"}</td><td>{x.stage_rate_method==="PER_1000"?"لكل ألف":x.stage_rate_method==="PER_PIECE"?"بالقطعة":x.stage_rate_method==="PER_HOUR"?"بالساعة":x.stage_rate_method==="PER_DAY"?"باليومية":x.stage_rate_method==="PERCENTAGE"?"نسبة":"—"}</td><td>{x.planned_quantity==null?"—":Number(x.planned_quantity).toLocaleString("ar-EG",{maximumFractionDigits:3})}</td><td>{Number(x.completed_quantity||0).toLocaleString("ar-EG",{maximumFractionDigits:3})}</td><td><span className="status">{x.status}</span></td><td>{has("orders.manage_stages")&&<div className="row-actions"><button className="secondary-btn" onClick={()=>editStage(x)}>تعديل</button><button className="primary-button" onClick={()=>beginPriceChange(x)}>تغيير السعر</button></div>}</td></tr>)}</tbody></table></div>
   </section>
   {has("orders.view")&&<section className="card" style={{marginBottom:16}}><div className="card-header"><div><h2 className="card-title">سجل تغييرات الأسعار</h2><div className="form-hint">كل تغيير محفوظ بسببه ونطاق تطبيقه وأثره على مستحقات العمال.</div></div><span className="count-badge">{priceChanges.length}</span></div><div className="table-wrap"><table><thead><tr><th>رقم الحركة</th><th>المرحلة</th><th>السعر السابق</th><th>السعر الجديد</th><th>نطاق التطبيق</th><th>العمليات المتأثرة</th><th>فرق المستحقات</th><th>تفاصيل فروق العمال</th><th>السبب</th><th>المستخدم</th><th>التاريخ</th></tr></thead><tbody>{priceChanges.map(x=><tr key={x.id}><td className="mono">{x.code}</td><td>{x.stage_name}</td><td>{x.previous_rate==null?"—":Number(x.previous_rate).toLocaleString("ar-EG",{maximumFractionDigits:4})}</td><td className="money">{Number(x.new_rate).toLocaleString("ar-EG",{maximumFractionDigits:4})}</td><td>{priceScopeLabels[x.scope]||x.scope}</td><td>{x.affected_entries}</td><td className="money">{Number(x.total_delta||0).toLocaleString("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2})} ج.م</td><td><div className="price-change-workers">{(x.affected||[]).map((a,i)=><div key={a.production_code||a.employee_name+String(i)}><strong>{a.employee_name}</strong><span>{a.production_code||"عملية"} · {Number(a.delta_amount||0).toLocaleString("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2})} ج.م</span></div>)}</div></td><td>{x.reason}</td><td>{x.created_by_username}</td><td>{new Date(x.created_at).toLocaleString("ar-EG")}</td></tr>)}{!priceChanges.length&&<tr><td colSpan={11}>لا توجد تغييرات أسعار مسجلة.</td></tr>}</tbody></table></div></section>}
   <div className="grid">
    <section className="card"><div className="card-header"><h2 className="card-title">إنتاج الطلب</h2></div><div className="table-wrap"><table><thead><tr><th>التاريخ</th><th>الموظف</th><th>المرحلة</th><th>النوع</th><th>الكمية</th><th>الأساسي</th><th>البونص</th><th>الخصم</th><th>تعديل السعر</th><th>إجمالي المستحق المعدّل</th><th>المدفوع</th><th>المتبقي</th><th>الحالة</th></tr></thead><tbody>{data.production.map(x=><tr key={x.id}><td>{x.work_date}</td><td>{x.employee_name}</td><td>{x.stage_name}</td><td>{x.production_type_name||"—"}</td><td>{Number(x.quantity).toLocaleString("ar-EG",{maximumFractionDigits:3})}</td><td>{Number(x.earning_amount||0).toLocaleString("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td>{Number(x.bonus_amount||0).toLocaleString("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td>{Number(x.deduction_amount||0).toLocaleString("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td className="money">{Number(x.price_adjustment_amount||0)===0?"—":Number(x.price_adjustment_amount).toLocaleString("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td className="money strong">{(Number(x.total_earning_amount||x.earning_amount||0)+Number(x.price_adjustment_amount||0)).toLocaleString("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td>{Number(x.paid_amount||0).toLocaleString("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td>{Number(x.remaining_amount||0).toLocaleString("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td><span className={"status "+(Number(x.remaining_amount||0)<=0&&x.status==="APPROVED"?"approved":"")}>{Number(x.remaining_amount||0)<=0&&x.status==="APPROVED"?"مدفوع بالكامل":x.status==="APPROVED"?"غير مكتمل الدفع":x.status==="PENDING"?"معلق":x.status}</span></td></tr>)}{!data.production.length&&<tr><td colSpan={13}>لا يوجد إنتاج مرتبط حتى الآن.</td></tr>}</tbody></table></div></section>
    <section className="card"><div className="card-header"><h2 className="card-title">مسحوبات المخزن</h2></div><div className="table-wrap"><table><thead><tr><th>التاريخ</th><th>المنتج</th><th>المخزن</th><th>الكمية</th><th>التكلفة</th></tr></thead><tbody>{data.movements.map(x=><tr key={x.code}><td>{new Date(x.created_at).toLocaleDateString("ar-EG")}</td><td>{x.product_name}</td><td>{x.warehouse_name}</td><td>{Number(x.quantity).toLocaleString("ar-EG",{maximumFractionDigits:3})}</td><td className="money">{Number(x.total_cost||0).toLocaleString("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2})}</td></tr>)}{!data.movements.length&&<tr><td colSpan={5}>لا توجد مسحوبات مرتبطة بالطلب.</td></tr>}</tbody></table></div></section>
   </div>
   <section className="card" style={{marginBottom:16}}><div className="card-header"><div><h2 className="card-title">مطابقة الطلب</h2><div className="form-hint">مقارنة المطلوب بالإنتاج المعتمد والتسليمات وحركة المخزن.</div></div><span className={recon?.ok?"status approved":"status rejected"}>{recon?(recon.ok?"متطابق":"يحتاج مراجعة"):"—"}</span></div><div className="table-wrap"><table><thead><tr><th>المنتج</th><th>المطلوب</th><th>الإنتاج المعتمد</th><th>المسلّم</th><th>خروج المخزن</th><th>دخول المخزن</th><th>فرق الإنتاج</th><th>فرق التسليم</th></tr></thead><tbody>{recon?.products.map(x=><tr key={x.productId}><td>{data?.production.find((p:any)=>p.product_id===x.productId)?.product_name||"—"}</td><td>{Number(x.ordered||0).toLocaleString("ar-EG",{maximumFractionDigits:3})}</td><td>{Number(x.produced||0).toLocaleString("ar-EG",{maximumFractionDigits:3})}</td><td>{Number(x.delivered||0).toLocaleString("ar-EG",{maximumFractionDigits:3})}</td><td>{Number(x.stockOut||0).toLocaleString("ar-EG",{maximumFractionDigits:3})}</td><td>{Number(x.stockIn||0).toLocaleString("ar-EG",{maximumFractionDigits:3})}</td><td>{Number(x.productionVariance||0).toLocaleString("ar-EG",{maximumFractionDigits:3})}</td><td>{Number(x.deliveryVariance||0).toLocaleString("ar-EG",{maximumFractionDigits:3})}</td></tr>)}{!recon?.products.length&&<tr><td colSpan={8}>لا توجد بيانات مطابقة بعد.</td></tr>}</tbody></table></div></section>
   <section className="card" style={{marginTop:16}}><div className="card-header"><h2 className="card-title">التسليمات</h2></div><div className="table-wrap"><table><thead><tr><th>الإذن</th><th>الوجهة</th><th>الكمية</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>{data.deliveries.map(x=><tr key={x.id}><td className="mono">{x.code}</td><td>{x.destination}</td><td>{Number(x.quantity).toLocaleString("ar-EG",{maximumFractionDigits:3})}</td><td>{x.status}</td><td>{new Date(x.created_at).toLocaleDateString("ar-EG")}</td></tr>)}{!data.deliveries.length&&<tr><td colSpan={5}>لا توجد تسليمات بعد.</td></tr>}</tbody></table></div></section>
  </section>
  {priceChangeStage&&<div className="modal-backdrop" onClick={()=>{if(!priceChangeSaving)setPriceChangeStage(null)}}><form className="modal-card" onSubmit={submitPriceChange} onClick={e=>e.stopPropagation()}><div className="card-header"><div><h2 className="card-title">تغيير سعر مرحلة</h2><div className="form-hint">{priceChangeStage.stage_name} · {priceChangeStage.output_product_name||"بدون منتج ناتج"}</div></div><button type="button" className="secondary-btn" onClick={()=>setPriceChangeStage(null)} disabled={priceChangeSaving}>إغلاق</button></div><div className="form-grid"><label>السعر الجديد<input inputMode="decimal" value={priceChangeRate} onChange={e=>setPriceChangeRate(e.target.value)} required/></label><label>نطاق تطبيق السعر<select value={priceChangeScope} onChange={e=>setPriceChangeScope(e.target.value as typeof priceChangeScope)}><option value="NEW_ONLY">الإنتاج الجديد فقط — لا تعديل على العمليات القديمة</option><option value="UNPAID_ONLY">العمليات غير المدفوعة فقط — المدفوع بالكامل لا يتغير</option><option value="ALL">كل العمليات — تسوية فروق مستحقات العمال</option></select></label><label style={{gridColumn:"1/-1"}}>سبب تغيير السعر<textarea value={priceChangeReason} onChange={e=>setPriceChangeReason(e.target.value)} minLength={2} maxLength={500} required placeholder="مثال: اتفاق جديد مع العميل أو تعديل سعر التشغيل"/></label></div><div className="alert" style={{margin:"0 18px 14px"}}>{priceChangeScope==="NEW_ONLY"?"سيُستخدم السعر الجديد في تسجيل الإنتاج القادم لهذه المرحلة، وتظل العمليات السابقة كما هي.":priceChangeScope==="UNPAID_ONLY"?"سيُطبق الفرق على العمليات التي لم يُسجل لها أي صرف فقط. العمليات المدفوعة جزئيًا أو بالكامل لن تدخل في التسوية.":"سيُحسب الفرق لكل عملية سابقة نشطة، ويُسجل في حركة مستحقات العامل بسبب تغيير سعر الطلبية. لو التخفيض سيقلل المستحق عن مبلغ صُرف بالفعل، سيرفض النظام العملية حمايةً للحسابات."}</div><div className="form-actions"><button type="button" className="secondary-btn" onClick={()=>setPriceChangeStage(null)} disabled={priceChangeSaving}>إلغاء</button><button className="primary-button" disabled={priceChangeSaving||!priceChangeRate.trim()||priceChangeReason.trim().length<2}>{priceChangeSaving?"جارٍ حساب الفروق...":"تأكيد تغيير السعر"}</button></div></form></div>}
  {editStageTarget&&<div className="modal-backdrop" onClick={()=>setEditStageTarget(null)}><section className="modal-card" role="dialog" aria-modal="true" aria-labelledby="edit-stage-title" onClick={e=>e.stopPropagation()}><div className="card-header"><div><h2 id="edit-stage-title" className="card-title">تعديل مرحلة الطلب</h2><div className="form-hint">التعديل هنا داخل النظام، من غير نوافذ المتصفح.</div></div><button type="button" className="secondary-btn" onClick={()=>setEditStageTarget(null)}>إغلاق</button></div><form onSubmit={saveStageEdit}><div className="form-grid"><label>اسم المرحلة<input value={editStageName} onChange={e=>setEditStageName(e.target.value)} required minLength={2}/></label><label>المنتج الناتج<input value={editStageProduct} onChange={e=>setEditStageProduct(e.target.value)} placeholder="اسم المنتج الناتج"/></label><label>حالة المرحلة<select value={editStageStatus} onChange={e=>setEditStageStatus(e.target.value)}><option value="PENDING">لم تبدأ</option><option value="READY">جاهزة</option><option value="IN_PROGRESS">قيد التشغيل</option><option value="COMPLETED">مكتملة</option><option value="CANCELLED">ملغاة</option></select></label></div><div className="form-actions"><button type="button" className="secondary-btn" onClick={()=>setEditStageTarget(null)}>إلغاء</button><button className="primary-button" disabled={savingStage||editStageName.trim().length<2}>{savingStage?"جارٍ الحفظ...":"حفظ التعديلات"}</button></div></form></section></div>}
 </main></div>;
}
