"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import {api} from "../../lib/api";
import {Sidebar,usePermissions} from "../../components/sidebar";
import {SearchableSelect} from "../../components/searchable-select";

type Item={id:string;code:string;name:string};
type Warehouse=Item&{address:string|null;location_count:number;warehouse_type:string;is_active:boolean};
type Location=Item&{warehouse_id:string;warehouse_name:string};
type Product=Item&{unit_name?:string;unit_id?:string;product_type?:string};
type Unit=Item&{symbol?:string;decimal_places?:number};
type Order=Item&{order_name:string};
type Stock={product_name:string;warehouse_name:string;location_name:string;quantity:number;unit_name:string;avg_unit_cost:number;inventory_value:number};
type Movement={code:string;movement_type:string;quantity:number;unit_cost:number|null;total_cost:number|null;product_name:string;product_code?:string;warehouse_name:string;location_name:string;created_at:string;order_code?:string|null;order_name?:string|null;created_by_username?:string|null;notes?:string|null};
type Cost={total_in:string;total_out:string;net:string;current_value:string;stock_lines:number};
type Lot={id:string;product_name:string;product_code:string;warehouse_name:string;location_name:string;batch_code:string|null;unit_cost:number;original_quantity:number;remaining_quantity:number;unit_name:string;source_type:string;created_at:string};
const labels:Record<string,string>={IN:"وارد",OUT:"صرف",RETURN:"مرتجع",ADJUSTMENT:"تسوية",TRANSFER_OUT:"تحويل"};
const warehouseTypes:Record<string,string>={GENERAL:"عام",RAW_MATERIAL:"خامات",WIP:"تحت التشغيل",FINISHED_GOODS:"منتجات جاهزة",SCRAP:"هالك"};

export default function WarehousePage(){
 const {has}=usePermissions();const [warehouses,setWarehouses]=useState<Warehouse[]>([]),[locations,setLocations]=useState<Location[]>([]),[products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[units,setUnits]=useState<Unit[]>([]),[stock,setStock]=useState<Stock[]>([]),[movements,setMovements]=useState<Movement[]>([]),[lots,setLots]=useState<Lot[]>([]),[cost,setCost]=useState<Cost|null>(null);
 const [warehouseId,setWarehouseId]=useState(""),[targetWarehouseId,setTargetWarehouseId]=useState(""),[productId,setProductId]=useState(""),[orderId,setOrderId]=useState(""),[movementType,setMovementType]=useState("IN"),[adjustmentDirection,setAdjustmentDirection]=useState("IN"),[quantity,setQuantity]=useState(""),[unitCost,setUnitCost]=useState(""),[notes,setNotes]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[year,setYear]=useState(""),[newWarehouse,setNewWarehouse]=useState(""),[warehouseType,setWarehouseType]=useState("GENERAL"),[showAddWarehouse,setShowAddWarehouse]=useState(false),[productSearch,setProductSearch]=useState(""),[newLocation,setNewLocation]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false),[locationToDisable,setLocationToDisable]=useState<Location|null>(null),[warehouseToDisable,setWarehouseToDisable]=useState<Warehouse|null>(null),[moveWarehouse,setMoveWarehouse]=useState(""),[moveLocation,setMoveLocation]=useState(""),[showQuickProduct,setShowQuickProduct]=useState(false),[quickProductName,setQuickProductName]=useState(""),[quickProductType,setQuickProductType]=useState("FINISHED_GOOD"),[quickProductUnit,setQuickProductUnit]=useState(""),[quickProductSaving,setQuickProductSaving]=useState(false);
 const [movementProductFilter,setMovementProductFilter]=useState(""),[movementOrderFilter,setMovementOrderFilter]=useState(""),[movementTypeFilter,setMovementTypeFilter]=useState(""),[movementSearch,setMovementSearch]=useState("");
 const [stockFilterProduct,setStockFilterProduct]=useState(""),[stockFilterWarehouse,setStockFilterWarehouse]=useState(""),[stockFilterSearch,setStockFilterSearch]=useState("");

 async function load(){
  setError("");
  try{const qs=new URLSearchParams();if(warehouseId)qs.set("warehouseId",warehouseId);if(from)qs.set("from",from);if(to)qs.set("to",to);const suffix=qs.toString()?"?"+qs.toString():"";const movementQs=new URLSearchParams(qs);if(movementProductFilter)movementQs.set("productId",movementProductFilter);if(movementOrderFilter)movementQs.set("orderId",movementOrderFilter);if(movementTypeFilter)movementQs.set("movementType",movementTypeFilter);if(movementSearch.trim())movementQs.set("q",movementSearch.trim());const movementSuffix=movementQs.toString()?"?"+movementQs.toString():"";const [w,l,p,o,u,s,m,c,lotData]=await Promise.all([api<{data:Warehouse[]}>("/api/warehouses"),api<{data:Location[]}>("/api/warehouse/locations"),api<{data:Product[]}>("/api/products"),api<{data:Order[]}>("/api/orders"),api<{data:Unit[]}>("/api/units"),api<{data:Stock[]}>("/api/warehouse/stock"+suffix),api<{data:Movement[]}>("/api/warehouse/movements"+movementSuffix),api<{data:Cost}>("/api/warehouse/dashboard"+suffix),api<{data:Lot[]}>("/api/warehouse/lots"+(warehouseId?"?warehouseId="+warehouseId:""))]);setWarehouses(w.data.filter(x=>x.is_active));setLocations(l.data);setProducts(p.data);setOrders(o.data);setUnits(u.data);if(!quickProductUnit)setQuickProductUnit(u.data.find(x=>x.code==="PCS")?.id||u.data[0]?.id||"");setStock(s.data);setMovements(m.data);setLots(lotData.data);setCost(c.data);if(!warehouseId&&w.data[0])setWarehouseId(w.data[0].id)}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل المخزن")}}
 useEffect(()=>{void load()},[from,to,warehouseId,movementProductFilter,movementOrderFilter,movementTypeFilter,movementSearch]);
 useEffect(()=>{if(year){setFrom(year+"-01-01");setTo(year+"-12-31")}},[year]);
 useEffect(()=>{if(warehouseId)void load()},[warehouseId]);

 const currentLocations=locations.filter(x=>x.warehouse_id===warehouseId),targetLocations=locations.filter(x=>x.warehouse_id===targetWarehouseId),productOptions=useMemo(()=>products.filter(x=>x.id).map(x=>({value:x.id,label:x.name})),[products]),warehouseOptions=useMemo(()=>warehouses.map(x=>({value:x.id,label:x.name,meta:warehouseTypes[x.warehouse_type]})),[warehouses]),orderOptions=useMemo(()=>orders.map(x=>({value:x.id,label:x.order_name,meta:x.code})),[orders]),visibleProducts=useMemo(()=>products.filter(x=>(x.code+" "+x.name).toLocaleLowerCase("ar-EG").includes(productSearch.trim().toLocaleLowerCase("ar-EG"))),[products,productSearch]);
 const filteredStock=useMemo(()=>stock.filter(x=>(!stockFilterProduct||x.product_name===stockFilterProduct)&&(!stockFilterWarehouse||x.warehouse_name===stockFilterWarehouse)&&(!stockFilterSearch||[x.product_name,x.warehouse_name,x.location_name].join(" ").toLowerCase().includes(stockFilterSearch.toLowerCase()))),[stock,stockFilterProduct,stockFilterWarehouse,stockFilterSearch]);
 const filteredLots=useMemo(()=>lots.filter(x=>(!stockFilterProduct||x.product_name===stockFilterProduct)&&(!stockFilterWarehouse||x.warehouse_name===stockFilterWarehouse)&&(!stockFilterSearch||[x.product_name,x.product_code,x.warehouse_name,x.location_name,x.batch_code||""].join(" ").toLowerCase().includes(stockFilterSearch.toLowerCase()))),[lots,stockFilterProduct,stockFilterWarehouse,stockFilterSearch]);
 const stockProducts=Array.from(new Set([...stock.map(x=>x.product_name),...lots.map(x=>x.product_name)])).sort((a,b)=>a.localeCompare(b,"ar"));
 const stockWarehouses=Array.from(new Set([...stock.map(x=>x.warehouse_name),...lots.map(x=>x.warehouse_name)])).sort((a,b)=>a.localeCompare(b,"ar"));

 function deactivateWarehouse(id:string){const w=warehouses.find(x=>x.id===id);if(w)setWarehouseToDisable(w)}
 async function confirmWarehouseDeactivate(){if(!warehouseToDisable)return;try{await api("/api/warehouses/"+warehouseToDisable.id,{method:"DELETE",body:JSON.stringify({targetWarehouseId:moveWarehouse||null,targetLocationId:moveLocation||null})});setWarehouseToDisable(null);setMoveWarehouse("");setMoveLocation("");await load()}catch(e){setError(e instanceof Error?e.message:"تعذر تعطيل المخزن أو نقل رصيده")}}
 async function deactivateLocation(){if(!locationToDisable)return;try{await api("/api/warehouse/locations/"+locationToDisable.id+"/deactivate",{method:"POST",body:JSON.stringify({targetWarehouseId:moveWarehouse||null,targetLocationId:moveLocation||null})});setLocationToDisable(null);setMoveWarehouse("");setMoveLocation("");await load()}catch(e){setError(e instanceof Error?e.message:"تعذر تعطيل المكان أو نقل رصيده")}}
 async function addQuickProduct(e:FormEvent){e.preventDefault();if(!quickProductName.trim()||!quickProductUnit)return;setQuickProductSaving(true);setError("");try{const result=await api<{data:Product}>("/api/products",{method:"POST",body:JSON.stringify({name:quickProductName.trim(),productType:quickProductType,unitId:quickProductUnit,minimumStock:0,trackInventory:true})});setProducts(v=>[...v.filter(x=>x.id!==result.data.id),result.data]);setProductId(result.data.id);setQuickProductName("");setShowQuickProduct(false);await load()}catch(e){setError(e instanceof Error?e.message:"تعذر إضافة الصنف")}finally{setQuickProductSaving(false)}}
 async function addWarehouse(e:FormEvent){e.preventDefault();setSaving(true);try{await api("/api/warehouses",{method:"POST",body:JSON.stringify({name:newWarehouse.trim(),warehouseType})});setNewWarehouse("");setWarehouseType("GENERAL");setShowAddWarehouse(false);await load()}catch(e){setError(e instanceof Error?e.message:"تعذر إضافة المخزن")}finally{setSaving(false)}}
 async function addLocation(e:FormEvent){e.preventDefault();try{await api("/api/warehouse/locations",{method:"POST",body:JSON.stringify({warehouseId,code:newLocation.toUpperCase(),name:newLocation})});setNewLocation("");await load()}catch(e){setError(e instanceof Error?e.message:"تعذر إضافة المكان")}}
 async function addMovement(e:FormEvent){e.preventDefault();setSaving(true);try{await api("/api/warehouse/movements",{method:"POST",body:JSON.stringify({movementType,productId,warehouseId,targetWarehouseId:movementType==="TRANSFER_OUT"?targetWarehouseId:undefined,quantity:Number(quantity),unitCost:unitCost?Number(unitCost):null,orderId:orderId||null,notes:notes||null,adjustmentDirection})});setQuantity("");setUnitCost("");setOrderId("");setNotes("");setTargetWarehouseId("");await load()}catch(e){setError(e instanceof Error?e.message:"تعذر تسجيل الحركة")}finally{setSaving(false)}}

 return <div className="app-shell"><Sidebar active="/warehouse"/><main className="main"><header className="topbar"><div><h1 className="page-title">المخزن والتكلفة</h1><p className="page-subtitle">الرصيد الحالي، تكلفة الداخل والخارج، وربط مسحوبات المخزن مباشرة بالطلبية.</p></div>{has("products.create")&&<button type="button" className="primary-button" onClick={()=>setShowQuickProduct(true)}>+ صنف سريع</button>}</header><section className="content">
  {error&&<div className="alert error">{error}</div>}
  <div className="stats"><article className="card stat"><div className="stat-label">قيمة المخزون الحالية</div><div className="stat-value">{Number(cost?.current_value||0).toLocaleString("ar-EG",{maximumFractionDigits:2})}</div><div className="stat-note">تكلفة الرصيد الحالي</div></article><article className="card stat accent"><div className="stat-label">تكلفة الداخل</div><div className="stat-value">{Number(cost?.total_in||0).toLocaleString("ar-EG",{maximumFractionDigits:2})}</div><div className="stat-note">حسب الفترة المحددة</div></article><article className="card stat warning"><div className="stat-label">تكلفة الخارج</div><div className="stat-value">{Number(cost?.total_out||0).toLocaleString("ar-EG",{maximumFractionDigits:2})}</div><div className="stat-note">الصرف والتحويلات</div></article><article className="card stat neutral"><div className="stat-label">صافي حركة التكلفة</div><div className="stat-value">{Number(cost?.net||0).toLocaleString("ar-EG",{maximumFractionDigits:2})}</div><div className="stat-note">داخل ناقص خارج</div></article></div>
  <section className="card" style={{marginBottom:16}}><div className="card-header"><div><h2 className="card-title">فلترة التكلفة</h2><div className="form-hint">اترك التاريخ فارغًا لعرض كل الفترة المسجلة.</div></div></div><div className="toolbar-grid"><label>من تاريخ<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>إلى تاريخ<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>السنة<select value={year} onChange={e=>setYear(e.target.value)}><option value="">كل السنوات</option>{[new Date().getFullYear(),new Date().getFullYear()-1,new Date().getFullYear()-2].map(y=><option key={y} value={String(y)}>{y}</option>)}</select></label><label>المخزن<SearchableSelect value={warehouseId} onChange={setWarehouseId} options={warehouseOptions} placeholder="كل المخازن"/></label></div></section>
  {has("warehouse.move")&&<section className="card form-card"><div className="card-header"><div><h2 className="card-title">تسجيل حركة مخزن</h2><div className="form-hint">لو الحركة خاصة بطلبية، اختارها هنا عشان تتسجل تكلفة المسحوب عليها تلقائيًا.</div></div></div><form className="production-grid" onSubmit={addMovement}>
   <label>نوع الحركة<select value={movementType} onChange={e=>{setMovementType(e.target.value);setTargetWarehouseId("")}}><option value="IN">استلام</option><option value="OUT">صرف / تسليم</option><option value="RETURN">مرتجع</option><option value="TRANSFER_OUT">تحويل بين المخازن</option><option value="ADJUSTMENT">تسوية</option></select></label><label>المنتج<SearchableSelect value={productId} onChange={setProductId} options={productOptions} placeholder="اختر المنتج"/></label><label>المخزن<SearchableSelect value={warehouseId} onChange={v=>{setWarehouseId(v)}} options={warehouseOptions} placeholder="اختر المخزن"/></label><label>الطلبية<SearchableSelect value={orderId} onChange={setOrderId} options={orderOptions} placeholder="اختياري — ربط بالطلب"/></label>
   {movementType==="TRANSFER_OUT"&&<label>المخزن المحوّل إليه<SearchableSelect value={targetWarehouseId} onChange={setTargetWarehouseId} options={warehouseOptions.filter(x=>x.value!==warehouseId)} placeholder="اختر المخزن المستلم"/></label>}<label>الكمية<input inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label><label>تكلفة الوحدة <span className="optional">(للوارد؛ الخارج يأخذ متوسط التكلفة)</span><input inputMode="decimal" value={unitCost} onChange={e=>setUnitCost(e.target.value)}/></label><label>اتجاه التسوية<select value={adjustmentDirection} onChange={e=>setAdjustmentDirection(e.target.value)} disabled={movementType!=="ADJUSTMENT"}><option value="IN">زيادة</option><option value="OUT">نقص</option></select></label><label style={{gridColumn:"1/-1"}}>ملاحظات<input value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="form-actions"><button className="primary-button" disabled={saving||!productId||!warehouseId||!quantity||(movementType==="TRANSFER_OUT"&&!targetWarehouseId)}>{saving?"جارٍ الحفظ...":"تسجيل الحركة"}</button></div>
  </form></section>}
<section className="card" style={{marginTop:16}}><div className="card-header"><div><h2 className="card-title">الأصناف والمنتجات</h2><div className="form-hint">قائمة الأصناف المستخدمة في المخزن. ابحث بالاسم أو الكود.</div></div><span className="count-badge">{visibleProducts.length}</span></div><div className="card-body coding-toolbar"><input value={productSearch} onChange={e=>setProductSearch(e.target.value)} placeholder="ابحث باسم الصنف أو الكود..."/></div><div className="table-wrap"><table><thead><tr><th>الكود</th><th>الصنف</th><th>الرصيد الحالي</th><th>متوسط التكلفة</th><th>قيمة الرصيد</th></tr></thead><tbody>{visibleProducts.map(p=>{const rows=stock.filter(s=>s.product_name===p.name);const qty=rows.reduce((n,s)=>n+Number(s.quantity||0),0);const value=rows.reduce((n,s)=>n+Number(s.inventory_value||0),0);const avg=qty?value/qty:0;return <tr key={p.id}><td className="mono strong">{p.code}</td><td className="strong">{p.name}</td><td>{qty.toLocaleString("ar-EG")}</td><td>{avg.toLocaleString("ar-EG",{maximumFractionDigits:4})}</td><td className="money">{value.toLocaleString("ar-EG",{maximumFractionDigits:2})}</td></tr>})}{!visibleProducts.length&&<tr><td colSpan={5}>لا توجد أصناف مطابقة.</td></tr>}</tbody></table></div></section>
<section className="card" style={{marginTop:16}}><div className="card-header"><div><h2 className="card-title">دفعات تكلفة الأصناف</h2><div className="form-hint">نفس الصنف يمكن أن يظهر بأكثر من سعر، وكل دفعة توضح مصدرها والرصيد المتبقي.</div></div><span className="count-badge">{lots.length}</span></div>
   <div className="form-grid finance-four-grid" style={{padding:16}}>
    <label>المنتج<select value={stockFilterProduct} onChange={e=>setStockFilterProduct(e.target.value)}><option value="">كل المنتجات</option>{stockProducts.map(x=><option key={x} value={x}>{x}</option>)}</select></label>
    <label>المخزن<select value={stockFilterWarehouse} onChange={e=>setStockFilterWarehouse(e.target.value)}><option value="">كل المخازن</option>{stockWarehouses.map(x=><option key={x} value={x}>{x}</option>)}</select></label>
    <label>بحث بالمنتج أو المكان أو الباتش<input value={stockFilterSearch} onChange={e=>setStockFilterSearch(e.target.value)} placeholder="اسم المنتج أو كود الدفعة"/></label>
    <div className="form-actions"><button type="button" className="secondary-button" onClick={()=>{setStockFilterProduct("");setStockFilterWarehouse("");setStockFilterSearch("")}}>مسح الفلاتر</button></div>
   </div><div className="table-wrap"><table><thead><tr><th>الصنف</th><th>المخزن</th><th>المكان</th><th>الدفعة</th><th>السعر</th><th>الأصلي</th><th>المتبقي</th><th>المصدر</th></tr></thead><tbody>{filteredLots.map(x=><tr key={x.id}><td><strong>{x.product_name}</strong><div className="form-hint">{x.product_code}</div></td><td>{x.warehouse_name}</td><td>{x.location_name}</td><td>{x.batch_code||"—"}</td><td className="money">{Number(x.unit_cost).toLocaleString("ar-EG",{maximumFractionDigits:4})}</td><td>{Number(x.original_quantity).toLocaleString("ar-EG",{maximumFractionDigits:3})} {x.unit_name}</td><td>{Number(x.remaining_quantity).toLocaleString("ar-EG",{maximumFractionDigits:3})} {x.unit_name}</td><td>{x.source_type}</td></tr>)}{!filteredLots.length&&<tr><td colSpan={8}>لا توجد دفعات مطابقة للفلاتر.</td></tr>}</tbody></table></div></section>
  <div className="grid"><section className="card"><div className="card-header"><div><h2 className="card-title">الأرصدة الحالية</h2><div className="form-hint">{filteredStock.length} رصيد مطابق للفلاتر.</div></div></div><div className="table-wrap"><table><thead><tr><th>المنتج</th><th>المخزن</th><th>المكان</th><th>الرصيد</th><th>متوسط التكلفة</th><th>قيمة الرصيد</th></tr></thead><tbody>{filteredStock.map((x,i)=><tr key={i}><td className="strong">{x.product_name}</td><td>{x.warehouse_name}</td><td>{x.location_name}</td><td>{Number(x.quantity).toLocaleString("ar-EG")} {x.unit_name}</td><td>{Number(x.avg_unit_cost||0).toLocaleString("ar-EG",{maximumFractionDigits:2})}</td><td className="money">{Number(x.inventory_value||0).toLocaleString("ar-EG",{maximumFractionDigits:2})}</td></tr>)}{!filteredStock.length&&<tr><td colSpan={6}>لا يوجد مخزون مطابق للفلاتر.</td></tr>}</tbody></table></div></section>
  <section className="card"><div className="card-header"><h2 className="card-title">سجل حركات المخزن</h2></div>
   <div className="form-grid finance-four-grid" style={{padding:16}}>
    <label>المنتج<select value={movementProductFilter} onChange={e=>setMovementProductFilter(e.target.value)}><option value="">كل المنتجات</option>{products.map(x=><option key={x.id} value={x.id}>{x.name} — {x.code}</option>)}</select></label>
    <label>الطلبية<select value={movementOrderFilter} onChange={e=>setMovementOrderFilter(e.target.value)}><option value="">كل الطلبيات</option>{orders.map(x=><option key={x.id} value={x.id}>{x.code} — {x.order_name}</option>)}</select></label>
    <label>نوع الحركة<select value={movementTypeFilter} onChange={e=>setMovementTypeFilter(e.target.value)}><option value="">كل أنواع الحركات</option><option value="IN">وارد</option><option value="OUT">صرف</option><option value="TRANSFER_IN">تحويل وارد</option><option value="TRANSFER_OUT">تحويل صادر</option><option value="RETURN">مرتجع</option><option value="ADJUSTMENT">تسوية</option></select></label>
    <label>بحث بالكود أو البيان أو الحساب<input value={movementSearch} onChange={e=>setMovementSearch(e.target.value)} placeholder="اسم المنتج، الكود، الحساب أو ملاحظات"/></label>
   </div>
   <div className="table-wrap"><table><thead><tr><th>النوع</th><th>المنتج</th><th>الطلبية</th><th>الكمية</th><th>تكلفة الوحدة</th><th>التكلفة</th><th>التاريخ</th><th>الحساب المسجّل</th><th>البيان</th></tr></thead><tbody>{movements.map(x=><tr key={x.code}><td>{labels[x.movement_type]||x.movement_type}</td><td>{x.product_name}<div className="form-hint">{x.product_code||""}</div></td><td>{x.order_code?x.order_code+" — "+(x.order_name||""):"—"}</td><td>{Number(x.quantity).toLocaleString("ar-EG",{maximumFractionDigits:3})}</td><td>{x.unit_cost==null?"—":Number(x.unit_cost).toLocaleString("ar-EG",{maximumFractionDigits:4})}</td><td className="money">{x.total_cost==null?"—":Number(x.total_cost).toLocaleString("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td>{new Date(x.created_at).toLocaleDateString("ar-EG")}</td><td>{x.created_by_username||"—"}</td><td>{x.notes||"—"}</td></tr>)}{!movements.length&&<tr><td colSpan={9}>لا توجد حركات مطابقة للفلاتر.</td></tr>}</tbody></table></div></section></div>
  {has("warehouse.manage")&&<div className="grid" style={{marginTop:16}}><section className="card"><div className="card-header"><h2 className="card-title">المخازن</h2><button type="button" className="secondary-btn" onClick={()=>setShowAddWarehouse(v=>!v)}>{showAddWarehouse?"إلغاء":"＋ إضافة مخزن"}</button></div>{showAddWarehouse&&<form className="card-body form-grid" onSubmit={addWarehouse}><label>اسم المخزن<input value={newWarehouse} onChange={e=>setNewWarehouse(e.target.value)} placeholder="مثال: مخزن التعبئة" required minLength={2} maxLength={120}/></label><label>نوع المخزن<select value={warehouseType} onChange={e=>setWarehouseType(e.target.value)}><option value="GENERAL">عام</option><option value="RAW_MATERIAL">خامات</option><option value="WIP">تحت التشغيل</option><option value="FINISHED_GOODS">منتجات جاهزة</option><option value="SCRAP">هالك</option></select></label><div className="form-actions" style={{gridColumn:"1/-1"}}><button className="primary-button" disabled={saving||newWarehouse.trim().length<2}>{saving?"جارٍ الحفظ...":"حفظ المخزن"}</button></div></form>}<div className="master-list">{warehouses.map(w=><div className="master-row" key={w.id}><strong>{w.name}</strong><span>{warehouseTypes[w.warehouse_type]||"عام"} · {w.location_count} مكان</span>{has("warehouses.delete")&&w.is_active?<button className="danger-button" onClick={()=>deactivateWarehouse(w.id)}>تعطيل</button>:null}</div>)}</div></section><section className="card"><div className="card-header"><h2 className="card-title">إضافة مكان للمخزن</h2></div><form className="inline-form" onSubmit={addLocation}><input value={newLocation} onChange={e=>setNewLocation(e.target.value)} placeholder="مثال A-01" required/><button className="primary-button" disabled={!warehouseId}>إضافة</button></form></section><section className="card"><div className="card-header"><div><h2 className="card-title">أماكن التخزين</h2><div className="form-hint">لو المكان عليه رصيد، النظام لن يسمح بالتعطيل إلا بعد اختيار مكان بديل ونقل الرصيد.</div></div></div><div className="master-list">{locations.map(l=><div className="master-row" key={l.id}><strong>{l.name}</strong><span>{l.warehouse_name} · {l.code}</span><button className="danger-button" onClick={()=>setLocationToDisable(l)}>تعطيل</button></div>)}</div></section></div>}

  {warehouseToDisable&&<div className="modal-backdrop" onClick={()=>{setWarehouseToDisable(null);setMoveWarehouse("");setMoveLocation("")}}><div className="modal-card" onClick={e=>e.stopPropagation()}><div className="card-header"><div><h2 className="card-title">تعطيل المخزن</h2><div className="form-hint">{warehouseToDisable.name}</div></div><button type="button" className="secondary-btn" onClick={()=>{setWarehouseToDisable(null);setMoveWarehouse("");setMoveLocation("")}}>إغلاق</button></div><div className="stack-form"><div className="alert" style={{margin:0}}>إذا كان المخزن عليه رصيد، سيتم نقله بالكامل إلى الوجهة المحددة ثم تعطيل المخزن. لن يتم حذف أي سجل تاريخي.</div><label>المخزن البديل<SearchableSelect value={moveWarehouse} onChange={v=>{setMoveWarehouse(v);setMoveLocation("")}} options={warehouseOptions.filter(x=>x.value!==warehouseToDisable.id)} placeholder="اختر المخزن البديل"/></label><label>المكان البديل<SearchableSelect value={moveLocation} onChange={setMoveLocation} options={locations.filter(x=>x.warehouse_id===moveWarehouse&&x.id!==locationToDisable?.id).map(x=>({value:x.id,label:x.name}))} placeholder="اختر المكان البديل" disabled={!moveWarehouse}/></label><div className="form-hint">لو المخزن فاضي، تقدر تضغط تعطيل مباشرة بدون اختيار وجهة.</div><div className="form-actions"><button type="button" className="secondary-btn" onClick={()=>{setWarehouseToDisable(null);setMoveWarehouse("");setMoveLocation("")}}>إلغاء</button><button type="button" className="danger-button" onClick={confirmWarehouseDeactivate}>نقل الرصيد وتعطيل</button></div></div></div></div>}
  {locationToDisable&&<div className="modal-backdrop" onClick={()=>setLocationToDisable(null)}><div className="modal-card" onClick={e=>e.stopPropagation()}><div className="card-header"><div><h2 className="card-title">تعطيل مكان التخزين</h2><div className="form-hint">{locationToDisable.warehouse_name} — {locationToDisable.name}</div></div><button type="button" className="secondary-btn" onClick={()=>setLocationToDisable(null)}>إغلاق</button></div><div className="stack-form"><div className="form-hint">إذا كان المكان عليه رصيد، اختر وجهة لنقل الرصيد إليها قبل التعطيل.</div><label>المخزن البديل<SearchableSelect value={moveWarehouse} onChange={v=>{setMoveWarehouse(v);setMoveLocation("")}} options={warehouseOptions} placeholder="اختر المخزن البديل"/></label><label>المكان البديل<SearchableSelect value={moveLocation} onChange={setMoveLocation} options={targetLocations.filter(x=>x.warehouse_id===moveWarehouse&&x.id!==locationToDisable.id).map(x=>({value:x.id,label:x.name}))} placeholder="اختر المكان البديل" disabled={!moveWarehouse}/></label><div className="form-actions"><button type="button" className="secondary-btn" onClick={()=>{setLocationToDisable(null);setMoveWarehouse("");setMoveLocation("")}}>إلغاء</button><button type="button" className="danger-button" onClick={deactivateLocation}>تعطيل / نقل الرصيد</button></div></div></div></div>}

 {showQuickProduct&&<div className="modal-backdrop" onClick={()=>{if(!quickProductSaving)setShowQuickProduct(false)}}><form className="modal-card" onSubmit={addQuickProduct} onClick={e=>e.stopPropagation()}><div className="card-header"><div><h2 className="card-title">إضافة صنف سريع</h2><div className="form-hint">سيظهر الصنف مباشرة في قوائم المخزن بعد الحفظ.</div></div><button type="button" className="secondary-btn" onClick={()=>setShowQuickProduct(false)} disabled={quickProductSaving}>إغلاق</button></div><div className="form-grid"><label>اسم الصنف<input autoFocus value={quickProductName} onChange={e=>setQuickProductName(e.target.value)} required minLength={2} placeholder="اسم الصنف"/></label><label>نوع الصنف<select value={quickProductType} onChange={e=>setQuickProductType(e.target.value)}><option value="FINISHED_GOOD">منتج جاهز</option><option value="RAW_MATERIAL">خامة</option><option value="COMPONENT">مكوّن</option><option value="CONSUMABLE">مستهلك</option><option value="SERVICE">خدمة</option></select></label><label>وحدة القياس<select value={quickProductUnit} onChange={e=>setQuickProductUnit(e.target.value)} required><option value="">اختر الوحدة</option>{units.filter(x=>x.id).map(x=><option key={x.id} value={x.id}>{x.name}{x.symbol?" ("+x.symbol+")":""}</option>)}</select></label></div><div className="form-actions"><button type="button" className="secondary-btn" onClick={()=>setShowQuickProduct(false)} disabled={quickProductSaving}>إلغاء</button><button className="primary-button" disabled={quickProductSaving||!quickProductName.trim()||!quickProductUnit}>{quickProductSaving?"جارٍ الحفظ...":"حفظ الصنف"}</button></div></form></div>} </section></main></div>;
}
