"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {api} from "../../lib/api";
import {Sidebar,usePermissions} from "../../components/sidebar";
import {SearchableSelect} from "../../components/searchable-select";

type Item={id:string;code:string;name:string};
type Machine=Item&{machine_type:string|null};
type Order={id:string;code:string;order_name:string};
type OrderStage={id:string;order_id:string;order_name:string;order_code:string;stage_name:string;stage_id:string;output_product_id:string|null;output_product_name:string|null};
type ProdType=Item;
type Row={id:string;code:string;work_date:string;quantity:string;machine_name:string;product_name:string;employee_name:string|null;order_code:string|null;order_name:string|null;stage_name:string|null;production_type_name:string|null};

export default function MachineProductionPage(){
 const {has}=usePermissions();const [machines,setMachines]=useState<Machine[]>([]),[products,setProducts]=useState<Item[]>([]),[employees,setEmployees]=useState<Item[]>([]),[shifts,setShifts]=useState<Item[]>([]),[orders,setOrders]=useState<Order[]>([]),[orderStages,setOrderStages]=useState<OrderStage[]>([]),[types,setTypes]=useState<ProdType[]>([]),[rows,setRows]=useState<Row[]>([]);
 const [name,setName]=useState(""),[machineType,setMachineType]=useState(""),[machine,setMachine]=useState(""),[product,setProduct]=useState(""),[employee,setEmployee]=useState(""),[shift,setShift]=useState(""),[orderId,setOrderId]=useState(""),[orderStage,setOrderStage]=useState(""),[productionType,setProductionType]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[qty,setQty]=useState(""),[notes,setNotes]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 async function load(){try{const [m,p,e,s,ord,o,t,r]=await Promise.all([api<{data:Machine[]}>("/api/machines"),api<{data:Item[]}>("/api/products"),api<{data:Item[]}>("/api/employees"),api<{data:Item[]}>("/api/shifts"),api<{data:Order[]}>("/api/orders"),api<{data:OrderStage[]}>("/api/order-stages"),api<{data:ProdType[]}>("/api/production-types"),api<{data:Row[]}>("/api/machine-production")]);setMachines(m.data);setProducts(p.data);setEmployees(e.data);setShifts(s.data);setOrders(ord.data);setOrderStages(o.data);setTypes(t.data);setRows(r.data);if(!machine&&m.data[0])setMachine(m.data[0].id);if(!product&&p.data[0])setProduct(p.data[0].id);if(!productionType&&t.data[0])setProductionType(t.data[0].id)}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل إنتاج الماكينات")}}
 useEffect(()=>{void load()},[]);
 const opts=(a:Item[])=>a.map(x=>({value:x.id,label:x.name}));
 const orderOpts=useMemo(()=>orders.map(x=>({value:x.id,label:x.order_name,meta:x.code})),[orders]);
 const availableProducts=useMemo(()=>products.filter(p=>orderStages.some(s=>s.order_id===orderId&&s.output_product_id===p.id)),[products,orderStages,orderId]);
 const stageOptions=useMemo(()=>orderStages.filter(s=>s.order_id===orderId&&s.output_product_id===product).map(s=>({value:s.id,label:s.stage_name,meta:s.output_product_name||"بدون منتج ناتج"})),[orderStages,orderId,product]);
 function selectOrder(v:string){setOrderId(v);setProduct("");setOrderStage("")}
 function selectProduct(v:string){setProduct(v);setOrderStage("")}
 function selectOrderStage(v:string){setOrderStage(v)}
 async function deactivateMachine(id:string){if(!confirm("تعطيل الماكينة؟"))return;try{await api("/api/machines/"+id,{method:"DELETE"});await load()}catch(e){setError(e instanceof Error?e.message:"تعذر تعطيل الماكينة")}}
 async function addMachine(e:FormEvent){e.preventDefault();try{await api("/api/machines",{method:"POST",body:JSON.stringify({name,machineType:machineType||undefined})});setName("");setMachineType("");await load()}catch(e){setError(e instanceof Error?e.message:"تعذر إضافة الماكينة")}}
 async function addProduction(e:FormEvent){e.preventDefault();if(!orderId)return setError("اختر الطلبية أولًا.");if(!product)return setError("اختر المنتج المرتبط بالطلبية.");if(!orderStage)return setError("اختر المرحلة المرتبطة بالمنتج.");setSaving(true);setError("");try{await api("/api/machine-production",{method:"POST",body:JSON.stringify({machineId:machine,productId:product,productionTypeId:productionType||null,orderStageId:orderStage,employeeId:employee||null,shiftId:shift||null,workDate:date,quantity:Number(qty),notes})});setQty("");setNotes("");await load()}catch(e){setError(e instanceof Error?e.message:"تعذر تسجيل إنتاج الماكينة")}finally{setSaving(false)}}
 return <div className="app-shell"><Sidebar active="/machine-production"/><main className="main"><header className="topbar"><div><h1 className="page-title">إنتاج الماكينات</h1><p className="page-subtitle">ربط إنتاج الماكينة بالطلب والمرحلة ونوع التشغيل مع ظهور الأسماء فقط.</p></div></header><section className="content">{error&&<div className="alert error">{error}</div>}
 {has("machines.create")&&<><form className="card mini-form" onSubmit={addMachine}><input placeholder="اسم الماكينة" value={name} onChange={e=>setName(e.target.value)} required/><input placeholder="نوع / وصف الماكينة" value={machineType} onChange={e=>setMachineType(e.target.value)}/><button className="primary-button">إضافة ماكينة</button></form><section className="card"><div className="card-header"><h2 className="card-title">الماكينات</h2></div><div className="master-list">{machines.map(x=><div className="master-row" key={x.id}><strong>{x.name}</strong><span>{x.machine_type||"بدون وصف"} · {x.code}</span>{has("machines.delete")?<button className="danger-button" onClick={()=>deactivateMachine(x.id)}>تعطيل</button>:null}</div>)}</div></section></>}
 {has("machine_production.create")&&<form className="card form-card" onSubmit={addProduction}><div className="card-header"><h2 className="card-title">تسجيل إنتاج ماكينة</h2></div><div className="form-grid">
 <label>الماكينة<SearchableSelect value={machine} onChange={setMachine} options={opts(machines)} placeholder="اختر الماكينة"/></label><label>الطلبية<SearchableSelect value={orderId} onChange={selectOrder} options={orderOpts} placeholder="اختر الطلبية"/></label><label>المنتج<SearchableSelect value={product} onChange={selectProduct} options={opts(availableProducts)} placeholder={orderId?"اختر منتجًا من الطلبية":"اختر الطلبية أولًا"}/></label><label>المرحلة<SearchableSelect value={orderStage} onChange={selectOrderStage} options={stageOptions} placeholder={product?"اختر مرحلة هذا المنتج":"اختر المنتج أولًا"}/></label><label>نوع الإنتاج<SearchableSelect value={productionType} onChange={setProductionType} options={opts(types)} placeholder="اختر النوع"/></label><label>الموظف<SearchableSelect value={employee} onChange={setEmployee} options={opts(employees)} placeholder="اختياري — الموظف"/></label><label>الوردية<SearchableSelect value={shift} onChange={setShift} options={opts(shifts)} placeholder="اختياري — الوردية"/></label><label>التاريخ<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>الكمية<input inputMode="decimal" value={qty} onChange={e=>setQty(e.target.value)} required/></label><label style={{gridColumn:"1/-1"}}>ملاحظات<input value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><div className="form-actions"><button className="primary-button" disabled={saving}>{saving?"جارٍ التسجيل...":"تسجيل الإنتاج"}</button></div></form>}
 <section className="card"><div className="card-header"><div><h2 className="card-title">سجل إنتاج الماكينات</h2><div className="form-hint">{machines.length} ماكينة نشطة</div></div></div><div className="table-wrap"><table><thead><tr><th>الماكينة</th><th>المنتج</th><th>نوع الإنتاج</th><th>الموظف</th><th>الطلب</th><th>المرحلة</th><th>الكمية</th><th>التاريخ</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.machine_name}</td><td>{x.product_name}</td><td>{x.production_type_name||"—"}</td><td>{x.employee_name??"—"}</td><td>{x.order_name||"—"}</td><td>{x.stage_name||"—"}</td><td>{Number(x.quantity).toLocaleString("ar-EG")}</td><td>{x.work_date}</td></tr>)}</tbody></table></div></section>
 </section></main></div>;
}
