"use client";
import {useEffect,useState} from "react";
import {api} from "../../lib/api";
type Summary={production:{entries:number;quantity:string;earnings:string};stock:{lines:number;quantity:string};earnings:{earned:string;debited:string;balance:string};pendingPayments:number;pendingAdvances:number};
type Audit={id:number;occurred_at:string;action:string;module:string;entity_type:string;username:string|null;employee_name:string|null};
export default function ReportsPage(){
 const [summary,setSummary]=useState<Summary|null>(null),[audit,setAudit]=useState<Audit[]>([]),[error,setError]=useState("");
 useEffect(()=>{Promise.all([api<{data:Summary}>("/api/reports/summary"),api<{data:Audit[]}>("/api/audit-log?limit=100")]).then(([s,a])=>{setSummary(s.data);setAudit(a.data)}).catch(e=>setError(e instanceof Error?e.message:"تعذر تحميل التقارير"))},[]);
 const n=(x:string|number)=>Number(x||0).toLocaleString("ar-EG",{maximumFractionDigits:2});
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"/><div className="brand-copy"><div className="brand-name">تيزكار</div><div className="brand-sub">إدارة المصنع</div></div></div><nav className="nav"><a className="nav-item" href="/"><span className="nav-icon">⌂</span><span>الرئيسية</span></a><a className="nav-item" href="/warehouse"><span className="nav-icon">▥</span><span>المخزن</span></a><a className="nav-item active" href="/reports"><span className="nav-icon">▦</span><span>التقارير</span></a></nav></aside>
 <main className="main"><header className="topbar"><div><h1 className="page-title">التقارير</h1><p className="page-subtitle">ملخص التشغيل والمستحقات وسجل العمليات</p></div></header><section className="content">{error&&<div className="alert error">{error}</div>}
 <div className="stats"><article className="card stat"><div className="stat-label">إنتاج اليوم</div><div className="stat-value">{summary?n(summary.production.quantity):"—"}</div><div className="stat-note">{summary?summary.production.entries+" سجل":"جاري التحميل"}</div></article><article className="card stat accent"><div className="stat-label">أرباح الإنتاج المعتمدة</div><div className="stat-value">{summary?n(summary.production.earnings):"—"}</div></article><article className="card stat warning"><div className="stat-label">صافي المستحقات</div><div className="stat-value">{summary?n(summary.earnings.balance):"—"}</div></article><article className="card stat neutral"><div className="stat-label">طلبات معلقة</div><div className="stat-value">{summary?summary.pendingPayments+summary.pendingAdvances:"—"}</div></article></div>
 <section className="card"><div className="card-header"><h2 className="card-title">ملخص مالي</h2></div><div className="card-body"><p>إجمالي المكتسب: <strong>{summary?n(summary.earnings.earned):"—"}</strong></p><p>إجمالي الخصم/الصرف: <strong>{summary?n(summary.earnings.debited):"—"}</strong></p><p>رصيد المستحقات: <strong>{summary?n(summary.earnings.balance):"—"}</strong></p></div></section>
 <section className="card"><div className="card-header"><h2 className="card-title">آخر العمليات</h2></div><div className="table-wrap"><table><thead><tr><th>الوقت</th><th>المستخدم</th><th>الموظف</th><th>الوحدة</th><th>العملية</th><th>الكيان</th></tr></thead><tbody>{audit.map(x=><tr key={x.id}><td>{new Date(x.occurred_at).toLocaleString("ar-EG")}</td><td>{x.username||"—"}</td><td>{x.employee_name||"—"}</td><td>{x.module}</td><td>{x.action}</td><td>{x.entity_type}</td></tr>)}{!audit.length&&<tr><td colSpan={6}>لا توجد عمليات مسجلة.</td></tr>}</tbody></table></div></section>
 </section></main></div>
}