"use client";
import { FormEvent, useEffect, useState } from "react";

const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000";
type Item={id:string;code:string;name:string};
type Employee={id:string;code:string;full_name:string};
type User={id:string;code:string;username:string;full_name:string|null;role_codes:string[];is_active:boolean};\ntype Permission={id:string;code:string;module:string;entity:string;action:string;scope:string|null};

export default function SettingsPage(){
 const [departments,setDepartments]=useState<Item[]>([]),[roles,setRoles]=useState<Item[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[users,setUsers]=useState<User[]>([]),[methods,setMethods]=useState<{code:string;name:string}[]>([]),[permissions,setPermissions]=useState<Permission[]>([]),[roleForPermissions,setRoleForPermissions]=useState(""),[rolePermissionIds,setRolePermissionIds]=useState<string[]>([]);
 const [message,setMessage]=useState(""),[error,setError]=useState("");
 const [deptCode,setDeptCode]=useState(""),[deptName,setDeptName]=useState("");
 const [jobCode,setJobCode]=useState(""),[jobName,setJobName]=useState(""),[jobDept,setJobDept]=useState("");
 const [username,setUsername]=useState(""),[password,setPassword]=useState(""),[role,setRole]=useState("worker"),[employee,setEmployee]=useState(""),[methodCode,setMethodCode]=useState(""),[methodName,setMethodName]=useState("");
 async function load(){
  const [d,j,r,u,e,m]=await Promise.all(["/api/departments","/api/job-titles","/api/roles","/api/users","/api/employees","/api/payment-methods"].map(p=>fetch(API+p,{credentials:"include"}).then(async x=>({ok:x.ok,b:await x.json()}))));
  if([d,j,r,u,e].some(x=>!x.ok)){window.location.replace("/login");return;}
  setDepartments(d.b.data);setRoles(r.b.data);setUsers(u.b.data);setEmployees(e.b.data);if(m.ok)setMethods(m.b.data);\n  if(r.ok){const pr=await fetch(API+"/api/permissions",{credentials:"include"});if(pr.ok){const pb=await pr.json();setPermissions(pb.data);}}
 }
 useEffect(()=>{load().catch(()=>window.location.replace("/login"));},[]);\n useEffect(()=>{if(!roleForPermissions&&roles[0])setRoleForPermissions(roles[0].id);},[roles,roleForPermissions]);\n useEffect(()=>{if(!roleForPermissions)return;fetch(API+"/api/roles/"+roleForPermissions+"/permissions",{credentials:"include"}).then(r=>r.json()).then(b=>setRolePermissionIds((b.data??[]).map((x:Permission)=>x.id))).catch(()=>setRolePermissionIds([]));},[roleForPermissions]);
 async function post(path:string,body:unknown){
  setError("");setMessage("");const res=await fetch(API+path,{method:"POST",headers:{"content-type":"application/json"},credentials:"include",body:JSON.stringify(body)});const b=await res.json();if(!res.ok)throw new Error(b?.error?.message??"تعذر تنفيذ العملية");return b;
 }
 async function addDept(e:FormEvent){e.preventDefault();try{await post("/api/departments",{code:deptCode,name:deptName});setDeptCode("");setDeptName("");setMessage("تم إضافة القسم");await load();}catch(x){setError(x instanceof Error?x.message:"حدث خطأ");}}
 async function addJob(e:FormEvent){e.preventDefault();try{await post("/api/job-titles",{code:jobCode,name:jobName,departmentId:jobDept||null});setJobCode("");setJobName("");setMessage("تم إضافة الوظيفة");await load();}catch(x){setError(x instanceof Error?x.message:"حدث خطأ");}}
 async function addUser(e:FormEvent){e.preventDefault();try{await post("/api/users",{username,password,roleCode:role,employeeId:employee||null});setUsername("");setPassword("");setMessage("تم إنشاء الحساب");await load();}catch(x){setError(x instanceof Error?x.message:"حدث خطأ");}}
 async function saveRolePermissions(){try{await post("/api/roles/"+roleForPermissions+"/permissions",{permissionIds:rolePermissionIds});setMessage("تم حفظ صلاحيات الدور");}catch(x){setError(x instanceof Error?x.message:"تعذر حفظ الصلاحيات");}}
 async function addMethod(e:FormEvent){e.preventDefault();try{await post("/api/payment-methods",{code:methodCode.trim().toUpperCase(),name:methodName.trim(),sortOrder:methods.length*10+10});setMethodCode("");setMethodName("");setMessage("تم إضافة طريقة القبض");await load();}catch(x){setError(x instanceof Error?x.message:"حدث خطأ");}}
 return <main className="settings-page">
  <header className="settings-header"><div><h1>الإعدادات والإدارة</h1><p>إدارة الهيكل الإداري وحسابات النظام</p></div><button className="secondary-btn" onClick={()=>window.location.replace("/")}>العودة للوحة التحكم</button></header>
  {message&&<div className="success-box">{message}</div>}{error&&<div className="auth-error">{error}</div>}
  <div className="settings-grid">
   <section className="card"><div className="section-title"><h3>الأقسام</h3></div><form className="mini-form" onSubmit={addDept}><input placeholder="الكود مثل PROD" value={deptCode} onChange={e=>setDeptCode(e.target.value)}/><input placeholder="اسم القسم" value={deptName} onChange={e=>setDeptName(e.target.value)}/><button className="primary-btn">إضافة قسم</button></form><div className="simple-list">{departments.map(x=><div key={x.id}><b>{x.code}</b><span>{x.name}</span></div>)}</div></section>
   <section className="card"><div className="section-title"><h3>الوظائف</h3></div><form className="mini-form" onSubmit={addJob}><input placeholder="الكود مثل SUPERVISOR" value={jobCode} onChange={e=>setJobCode(e.target.value)}/><input placeholder="اسم الوظيفة" value={jobName} onChange={e=>setJobName(e.target.value)}/><select value={jobDept} onChange={e=>setJobDept(e.target.value)}><option value="">بدون قسم</option>{departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="primary-btn">إضافة وظيفة</button></form></section>
   <section className="card settings-wide"><div className="section-title"><h3>حسابات المستخدمين</h3></div><form className="user-form" onSubmit={addUser}><input placeholder="اسم المستخدم" value={username} onChange={e=>setUsername(e.target.value)}/><input placeholder="كلمة المرور — 12 حرفًا على الأقل" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(x=><option key={x.id} value={x.code}>{x.name}</option>)}</select><select value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">حساب بدون موظف</option>{employees.map(x=><option key={x.id} value={x.id}>{x.code} — {x.full_name}</option>)}</select><button className="primary-btn">إنشاء حساب</button></form><table className="table"><thead><tr><th>المستخدم</th><th>الموظف</th><th>الدور</th><th>الحالة</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.username}</td><td>{u.full_name??"—"}</td><td>{u.role_codes.join("، ")||"—"}</td><td><span className="status">{u.is_active?"نشط":"موقوف"}</span></td></tr>)}</tbody></table></section>
  <section className="card settings-wide"><div className="section-title"><h3>صلاحيات الأدوار</h3></div><div className="user-form"><select value={roleForPermissions} onChange={e=>setRoleForPermissions(e.target.value)}>{roles.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button type="button" className="primary-btn" onClick={saveRolePermissions}>حفظ صلاحيات الدور</button></div><div className="master-list" style={{maxHeight:420,overflow:"auto",marginTop:12}}>{permissions.map(p=><label key={p.id} className="master-row" style={{cursor:"pointer"}}><input type="checkbox" checked={rolePermissionIds.includes(p.id)} onChange={e=>setRolePermissionIds(v=>e.target.checked?[...v,p.id]:v.filter(id=>id!==p.id))}/><span className="mono">{p.code}</span><strong>{p.module}</strong><span>{p.entity} · {p.action}{p.scope?" · "+p.scope:""}</span></label>)}</div></section>
  <section className="card settings-wide"><div className="section-title"><h3>طرق القبض</h3></div><form className="mini-form" onSubmit={addMethod}><input placeholder="الكود مثل BANK_TRANSFER" value={methodCode} onChange={e=>setMethodCode(e.target.value)}/><input placeholder="اسم الطريقة" value={methodName} onChange={e=>setMethodName(e.target.value)}/><button className="primary-btn">إضافة طريقة</button></form><div className="simple-list">{methods.map(x=><div key={x.code}><b>{x.code}</b><span>{x.name}</span></div>)}</div></section></div>
 </main>;
}