"use client";
import { FormEvent,useEffect,useState } from "react";
const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000";
type O={id:string;code:string;name:string};
export default function OperationsPage(){
 const [shifts,setShifts]=useState<any[]>([]),[groups,setGroups]=useState<O[]>([]),[units,setUnits]=useState<O[]>([]),[products,setProducts]=useState<any[]>([]),[stages,setStages]=useState<O[]>([]),[wages,setWages]=useState<any[]>([]),[employees,setEmployees]=useState<any[]>([]);
 const [tab,setTab]=useState("shifts"),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 const [shiftName,setShiftName]=useState(""),[start,setStart]=useState("08:00"),[end,setEnd]=useState("16:00"),[group,setGroup]=useState(""),[night,setNight]=useState(false),[leaderShift,setLeaderShift]=useState(""),[leaderEmployee,setLeaderEmployee]=useState("");
 const [groupName,setGroupName]=useState(""),[stageName,setStageName]=useState(""),[productName,setProductName]=useState(""),[productType,setProductType]=useState("FINISHED_GOOD"),[unit,setUnit]=useState("");
 async function get(path:string){const r=await fetch(API+path,{credentials:"include"});const b=await r.json();if(!r.ok)throw new Error(b?.error?.message??"تعذر تحميل البيانات");return b.data;}
 async function load(){const [s,g,u,p,st,w,e]=await Promise.all(["/api/shifts","/api/rate-groups","/api/units","/api/products","/api/stages","/api/wage-types","/api/employees"].map(get));setShifts(s);setGroups(g);setUnits(u);setProducts(p);setStages(st);setWages(w);setEmployees(e);if(!group&&g[0])setGroup(g[0].id);if(!unit&&u[0])setUnit(u[0].id);}
 useEffect(()=>{load().catch(()=>window.location.replace("/login"));},[]);
 async function post(path:string,body:any){setErr("");setMsg("");const r=await fetch(API+path,{method:"POST",headers:{"content-type":"application/json"},credentials:"include",body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw new Error(b?.error?.message??"تعذر الحفظ");return b.data;}
 async function addGroup(e:FormEvent){e.preventDefault();try{await post("/api/rate-groups",{name:groupName});setGroupName("");setMsg("تم إنشاء مجموعة الأجر");await load();}catch(x){setErr(x instanceof Error?x.message:"حدث خطأ");}}
 async function addShift(e:FormEvent){e.preventDefault();try{await post("/api/shifts",{name:shiftName,startTime:start,endTime:end,crossesMidnight:night,rateGroupId:group});setShiftName("");setMsg("تم إنشاء الوردية");await load();}catch(x){setErr(x instanceof Error?x.message:"حدث خطأ");}}
 async function addLeader(e:FormEvent){e.preventDefault();try{await post(`/api/shifts/${leaderShift}/leaders`,{employeeId:leaderEmployee});setMsg("تم تعيين قائد الوردية");}catch(x){setErr(x instanceof Error?x.message:"حدث خطأ");}}\n async function addStage(e:FormEvent){e.preventDefault();try{await post("/api/stages",{name:stageName});setStageName("");setMsg("تم إنشاء المرحلة");}catch(x){setErr(x instanceof Error?x.message:"مرحلة التشغيل");}}
 async function addProduct(e:FormEvent){e.preventDefault();try{await post("/api/products",{name:productName,productType,unitId:unit,minimumStock:0,trackInventory:true});setProductName("");setMsg("تم إنشاء المنتج");await load();}catch(x){setErr(x instanceof Error?x.message:"حدث خطأ");}}
 return <main className="settings-page"><header className="settings-header"><div><h1>التشغيل والبيانات الأساسية</h1><p>الورديات، مجموعات الأجور، مراحل التشغيل والمنتجات</p></div><button className="secondary-btn" onClick={()=>window.location.replace("/")}>لوحة التحكم</button></header>
 {msg&&<div className="success-box">{msg}</div>}{err&&<div className="auth-error">{err}</div>}
 <div className="master-tabs">{[["shifts","الورديات"],["groups","مجموعات الأجر"],["products","المنتجات"],["stages","مراحل التشغيل"],["units","الوحدات"],["wages","أنواع الأجر"]].map(x=><button className={tab===x[0]?"active":""} key={x[0]} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>
 {tab==="shifts"&&<section className="card"><div className="section-title"><h3>الورديات</h3></div><form className="user-form" onSubmit={addShift}><input placeholder="اسم الوردية" value={shiftName} onChange={e=>setShiftName(e.target.value)}/><input type="time" value={start} onChange={e=>setStart(e.target.value)}/><input type="time" value={end} onChange={e=>setEnd(e.target.value)}/><select value={group} onChange={e=>setGroup(e.target.value)}><option value="">مجموعة الأجر</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><label className="check"><input type="checkbox" checked={night} onChange={e=>setNight(e.target.checked)}/> تمتد لليوم التالي</label><button className="primary-btn">إضافة وردية</button></form><div className="sub-block"><h4>تعيين قائد وردية</h4><form className="user-form" onSubmit={addLeader}><select value={leaderShift} onChange={e=>setLeaderShift(e.target.value)}><option value="">اختر الوردية</option>{shifts.map(s=><option key={s.id} value={s.id}>{s.name} — {s.code}</option>)}</select><select value={leaderEmployee} onChange={e=>setLeaderEmployee(e.target.value)}><option value="">اختر الموظف</option>{employees.map(e=><option key={e.id} value={e.id}>{e.code} — {e.full_name}</option>)}</select><button className="primary-btn">تعيين القائد</button></form></div><table className="table"><thead><tr><th>الكود</th><th>الوردية</th><th>الوقت</th><th>مجموعة الأجر</th></tr></thead><tbody>{shifts.map(s=><tr key={s.id}><td>{s.code}</td><td>{s.name}</td><td>{String(s.start_time).slice(0,5)} — {String(s.end_time).slice(0,5)}</td><td>{s.rate_group_name}</td></tr>)}</tbody></table></section>}
 {tab==="groups"&&<section className="card"><div className="section-title"><h3>مجموعات الأجور</h3></div><form className="mini-form" onSubmit={addGroup}><input placeholder="اسم المجموعة" value={groupName} onChange={e=>setGroupName(e.target.value)}/><button className="primary-btn">إضافة مجموعة</button></form><div className="simple-list">{groups.map(g=><div key={g.id}><b>{g.code}</b><span>{g.name}</span></div>)}</div></section>}
 {tab==="products"&&<section className="card"><div className="section-title"><h3>المنتجات</h3></div><form className="user-form" onSubmit={addProduct}><input placeholder="اسم المنتج" value={productName} onChange={e=>setProductName(e.target.value)}/><select value={productType} onChange={e=>setProductType(e.target.value)}><option value="FINISHED_GOOD">منتج تام</option><option value="RAW_MATERIAL">خامة</option><option value="COMPONENT">مكوّن</option><option value="CONSUMABLE">مستهلك</option><option value="SERVICE">خدمة</option></select><select value={unit} onChange={e=>setUnit(e.target.value)}>{units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><button className="primary-btn">إضافة منتج</button></form><table className="table"><thead><tr><th>الكود</th><th>المنتج</th><th>النوع</th><th>الوحدة</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.code}</td><td>{p.name}</td><td>{p.product_type}</td><td>{p.unit_name}</td></tr>)}</tbody></table></section>}
 {tab==="stages"&&<section className="card"><div className="section-title"><h3>مراحل التشغيل</h3></div><form className="mini-form" onSubmit={addStage}><input placeholder="اسم المرحلة" value={stageName} onChange={e=>setStageName(e.target.value)}/><button className="primary-btn">إضافة مرحلة</button></form><div className="simple-list">{stages.map(s=><div key={s.id}><b>{s.code}</b><span>{s.name}</span></div>)}</div></section>}
 {tab==="units"&&<section className="card"><div className="section-title"><h3>وحدات القياس</h3></div><div className="simple-list">{units.map(u=><div key={u.id}><b>{u.code}</b><span>{u.name} — {u.symbol??""}</span></div>)}</div></section>}
 {tab==="wages"&&<section className="card"><div className="section-title"><h3>أنواع الأجر</h3></div><div className="simple-list">{wages.map(w=><div key={w.id}><b>{w.code}</b><span>{w.name} — {w.method}</span></div>)}</div></section>}
 </main>;